### ISSUE TITLE
Can not deserialize instance of java.util.LinkedHashMap out of START_OBJECT token

### ISSUE THREAD

**Issue by kstamos-code** [knowm/XChange#1824]
Using latest develop branch

my main looks like:

`package main;

import java.io.IOException;
import java.util.Map;

import org.knowm.xchange.BaseExchange;
import org.knowm.xchange.ExchangeFactory;
import org.knowm.xchange.ExchangeSpecification;
import org.knowm.xchange.poloniex.PoloniexExchange;
import org.knowm.xchange.poloniex.dto.trade.PoloniexOpenOrder;
import org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw;
import org.knowm.xchange.service.trade.TradeService;

import config.Config;

public class Skata {
	public static void main(final String[] args) throws IOException {
		final ExchangeSpecification spec = new ExchangeSpecification(PoloniexExchange.class);
		spec.setApiKey(Config.API_KEY);
		spec.setSecretKey(Config.PRIVATE_API_KEY);

		final BaseExchange exchange = (BaseExchange) ExchangeFactory.INSTANCE.createExchange(spec);
		final TradeService tradeService = exchange.getTradeService();
		final Map<String, PoloniexOpenOrder[]> returnOrder = ((PoloniexTradeServiceRaw) tradeService)
				.returnOrder("8893054227");
	}
}`

and I get:

`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/kstamos/Documents/eclipse-workspace/libs/apache-activemq-5.15.0/activemq-all-5.15.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/kstamos/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
 INFO | Calling Remote Init...
 WARN | Noncritical error parsing error output: [{"globalTradeID":244256733,"tradeID":829696,"currencyPair":"BTC_NXC","type":"buy","rate":"0.00004359","amount":"69.44444444","total":"0.00302708","fee":"0.00150000","date":"2017-10-17 21:32:15"}]
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.knowm.xchange.poloniex.PoloniexException out of START_ARRAY token
 at [Source: [{"globalTradeID":244256733,"tradeID":829696,"currencyPair":"BTC_NXC","type":"buy","rate":"0.00004359","amount":"69.44444444","total":"0.00302708","fee":"0.00150000","date":"2017-10-17 21:32:15"}]; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1233)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1121)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1368)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:174)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2871)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy12.returnOrderTrades(Unknown Source)
	at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.returnOrder(PoloniexTradeServiceRaw.java:43)
	at main.Skata.main(Skata.java:25)
Exception in thread "main" si.mazi.rescu.HttpStatusIOException: Can not deserialize instance of java.util.LinkedHashMap out of START_OBJECT token
 at [Source: [{"globalTradeID":244256733,"tradeID":829696,"currencyPair":"BTC_NXC","type":"buy","rate":"0.00004359","amount":"69.44444444","total":"0.00302708","fee":"0.00150000","date":"2017-10-17 21:32:15"}]; line: 1, column: 2]
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy12.returnOrderTrades(Unknown Source)
	at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.returnOrder(PoloniexTradeServiceRaw.java:43)
	at main.Skata.main(Skata.java:25)
`

**Comment by timmolter** [comment]
Maybe they changed their JSON. See what JSON is returned, make a unit test for it or modify an existing one, fix it and submit a PR with the fix.

**Comment by iPretendILoveToCode** [comment]
I am afraid I do not have the resources to do it at the moment.
I will try to have a look in the next few days.

**Comment by jovi521** [comment]
got it!
