### ISSUE TITLE
Kraken TradeService getting a NPE for getTradeHistory

### ISSUE THREAD

**Issue by KIC** [knowm/XChange#1826]
Maybe I do somehting wrong but at least it feels valid what I try to do :-)

Works:
```
       TradeService tradeService = kraken.getTradeService();
        Map<String, KrakenTrade> krakenTradeHistory = ((KrakenTradeService) tradeService).getKrakenTradeHistory();
        System.out.println(krakenTradeHistory);

```

Gets NPE:
```
       TradeService tradeService = kraken.getTradeService();
        UserTrades tradeHistory = tradeService.getTradeHistory(new TradeHistoryParamsAll());
        System.out.println(tradeHistory);
```

```
Exception in thread "main" java.lang.NullPointerException
	at org.knowm.xchange.kraken.KrakenAdapters.adaptTrade(KrakenAdapters.java:217)
	at org.knowm.xchange.kraken.KrakenAdapters.adaptTradesHistory(KrakenAdapters.java:200)
	at org.knowm.xchange.kraken.service.KrakenTradeService.getTradeHistory(KrakenTradeService.java:100)

```

**Comment by digitalchaotics** [comment]
I solved this problem by passing a more full-featured TradeHistoryParams object, and in this case making sure that the Currency is set.  It does mean that there's no "all" option, however.

```
public class TradeHistoryParamsCurrencyTimeSpan implements TradeHistoryParams, TradeHistoryParamCurrency, TradeHistoryParamsTimeSpan {
    private Currency currency;
    private Date startTime;
    private Date endTime;

    public TradeHistoryParamsCurrencyTimeSpan(Currency currency, Date startTime, Date endTime) {
        this.currency = currency;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    @Override
    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    @Override
    public Currency getCurrency() {
        return currency;
    }

    @Override
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Override
    public Date getStartTime() {
        return startTime;
    }

    @Override
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Override
    public Date getEndTime() {
        return endTime;
    }
}

```

**Comment by KIC** [comment]
using this i stillget a NPE 

```
static class Foo implements TradeHistoryParams, TradeHistoryParamCurrency, TradeHistoryParamsTimeSpan {

        @Override
        public void setCurrency(Currency currency) {

        }

        @Override
        public Currency getCurrency() {
            return new Currency("BTC");
        }

        @Override
        public void setStartTime(Date startTime) {

        }

        @Override
        public Date getStartTime() {
            return new Date(0);
        }

        @Override
        public void setEndTime(Date endTime) {

        }

        @Override
        public Date getEndTime() {
            return new Date(Long.MAX_VALUE);
        }
    }
```

**Comment by Achterhoeker** [comment]
@KIC same as https://github.com/timmolter/XChange/issues/1812 ?
Problem there is that a currency pair from the past is not available anymore. (ltc/btc switched) The adapter doesn;t know how to handle this strange pair as it isn't signalled anymore.

**Comment by KIC** [comment]
yep. i have also tried different currencies also from the constants ... same result. 

```
Exception in thread "main" java.lang.NullPointerException
	at org.knowm.xchange.kraken.KrakenAdapters.adaptTrade(KrakenAdapters.java:217)
	at org.knowm.xchange.kraken.KrakenAdapters.adaptTradesHistory(KrakenAdapters.java:200)
	at org.knowm.xchange.kraken.service.KrakenTradeService.getTradeHistory(KrakenTradeService.java:100)

```

**Comment by npomfret** [comment]
> ltc/btc switched

It used to come back from the exchange as BTC/LTC?
