### ISSUE TITLE
LiquiExchange missing json file

### ISSUE THREAD

**Issue by cowwoc** [knowm/XChange#2038]
LiquiExchange is missing a json file so it throws an exception every time on startup:

```
04:24:49.501 [main] WARN  o.knowm.xchange.liqui.LiquiExchange - An exception occured while loading the metadata file from the file system. This is just a warning and can be ignored, but it may lead to unexpected results, so it's better to address it.
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2908)
	at org.knowm.xchange.BaseExchange.loadMetaData(BaseExchange.java:137)
	at org.knowm.xchange.BaseExchange.loadExchangeMetaData(BaseExchange.java:128)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:96)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:98)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:147)
```

**Comment by MirkoTeran** [comment]
Is there any workaround for this until it gets fixed?

**Comment by earce** [comment]
Exchange defunct
