### ISSUE TITLE
LiquiExchange MismatchedInputException on get symbols

### ISSUE THREAD

**Issue by archenroot** [knowm/XChange#2123]
While obtaining exchange symbols I get following error:
```
11:40:44.643 [default] [main] WARN  o.knowm.xchange.liqui.LiquiExchange - An exception occured while loading the metadata file from the file system. This is just a warning and can be ignored, but it may lead to unexpected results, so it's better to address it. com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4134)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058)
	at org.knowm.xchange.BaseExchange.loadMetaData(BaseExchange.java:137)
	at org.knowm.xchange.BaseExchange.loadExchangeMetaData(BaseExchange.java:128)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:96)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:134)
	at org.prokyon.cryptotrader.exchanges.LiquiExchangeConnection.createInstance(LiquiExchangeConnection.java:24)
	at org.prokyon.cryptotrader.exchanges.LiquiExchangeConnection.getInstance(LiquiExchangeConnection.java:30)
	at org.prokyon.cryptotrader.exchanges.MarketExchange$19.getExchange(MarketExchange.java:61)
	at org.prokyon.exchange_trader.orderbook_feeder.playground.Main.main(Main.java:30)

```

**Comment by earce** [comment]
Defunct exchange
