### ISSUE TITLE
Binance handshake_failure

### ISSUE THREAD

**Issue by mrhead66** [knowm/XChange#2445]
Receiving this when running from unix using binance 4.3.5-SNAPSHOT.... anyone seen this before? Just checked, also have the same issue on Windows too.  

018-03-27 23:13:40,469 Thread-1 Error updating Binance
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_65]
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[?:1.8.0_65]
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023) ~[?:1.8.0_65]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125) ~[?:1.8.0_65]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_65]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[?:1.8.0_65]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[?:1.8.0_65]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_65]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_65]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[?:1.8.0_65]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1441) ~[?:1.8.0_65]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_65]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[?:1.8.0_65]
        at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:122) ~[app.jar:?]
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:155) ~[app.jar:?]
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119) ~[app.jar:?]
        **at com.sun.proxy.$Proxy57.time(Unknown Source) ~[?:?]
        at org.knowm.xchange.binance.BinanceExchange.deltaServerTime(BinanceExchange.java:153) ~[app.jar:?]**
        at org.knowm.xchange.binance.service.BinanceBaseService.getTimestamp(BinanceBaseService.java:37) ~[app.jar:?]
        at org.knowm.xchange.binance.service.BinanceAccountService.getAccountInfo(BinanceAccountService.java:75) ~[app.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

**Comment by mrhead66** [comment]
This has been caused by Binance updating to TLS 1.2
