### ISSUE TITLE
Bitmex : 400 error on getAccountInfo

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#2539]
Code :

```
final ExchangeSpecification exSpec = new BitmexExchange().getDefaultExchangeSpecification();
exSpec.setApiKey("XXXX");
exSpec.setSecretKey("YYYY");

final Exchange bitmex = ExchangeFactory.INSTANCE.createExchange(exSpec);
final AccountService accountService = bitmex.getAccountService();
final AccountInfo accountInfo = accountService.getAccountInfo();
```

Stacktrace :

> Exception in thread "main" si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 400
> 	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
> 	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
> 	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
> 	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
> 	at com.sun.proxy.$Proxy10.getAccount(Unknown Source)
> 	at org.knowm.xchange.bitmex.service.BitmexAccountServiceRaw.getBitmexAccountInfo(BitmexAccountServiceRaw.java:31)
> 	at org.knowm.xchange.bitmex.service.BitmexAccountService.getAccountInfo(BitmexAccountService.java:33)
>

**Comment by wvr** [comment]
@trixprod just checked this and it's working for me without problems. Could you re-check and close if not a problem anymore?

**Comment by mdvx** [comment]
any resolution on this?
Caused by: java.lang.NullPointerException
	at org.knowm.xchange.bitmex.service.BitmexDigest.digestParams(BitmexDigest.java:45) ~[classes/:?]
	at si.mazi.rescu.Params.digestAll(Params.java:199) ~[rescu-2.0.2.jar:?]
	at si.mazi.rescu.RestInvocation.create(RestInvocation.java:147) ~[rescu-2.0.2.jar:?]
	at si.mazi.rescu.RestInvocationHandler.createInvocation(RestInvocationHandler.java:188) ~[rescu-2.0.2.jar:?]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:116) ~[rescu-2.0.2.jar:?]
	at com.sun.proxy.$Proxy51.getAccount(Unknown Source) ~[?:?]
	at org.knowm.xchange.bitmex.service.BitmexAccountServiceRaw.lambda$getBitmexAccountInfo$0(BitmexAccountServiceRaw.java:31) ~[classes/:?]
	at org.knowm.xchange.bitmex.service.BitmexBaseService.updateRateLimit(BitmexBaseService.java:75) ~[classes/:?]
