### ISSUE TITLE
Bitmex getOrderBook exception processing null arguments

### ISSUE THREAD

**Issue by ThomasWick** [knowm/XChange#2601]
getOrderBook function called from BitmexMarketDataService class throws an IllegalArgumentException when no optional arguments are passed args[ ].

Exception in thread "main" java.lang.IllegalArgumentException: 1 > 0
	at java.util.Arrays.copyOfRange(Arrays.java:3480)
	at java.util.Arrays.copyOfRange(Arrays.java:3441)
	at org.knowm.xchange.bitmex.service.BitmexMarketDataService.getOrderBook(BitmexMarketDataService.java:91)
```

args array needs to be checked before executing Arrays.copyOfRange()

  public OrderBook getOrderBook(CurrencyPair currencyPair, Object... args) throws IOException {

    BitmexPrompt prompt = null;
    if (args != null && args.length > 0) {
      Object arg0 = args[0];
      if (arg0 instanceof BitmexPrompt) {
        prompt = (BitmexPrompt) arg0;
      } else {
        throw new ExchangeException("args[0] must be of type BitmexPrompt!");
      }
    }
    **Object[] argsToPass = Arrays.copyOfRange(args, 1, args.length);**
    return BitmexAdapters.adaptOrderBook(
        getBitmexDepth(BitmexAdapters.adaptCurrencyPair(currencyPair), prompt, argsToPass),
        currencyPair);
  }
```

Happy for this to be my maiden contribution if the community believes it needs a fix? :)

**Comment by wvr** [comment]
@ThomasWick I'm checking a few issues pertaining to bitmex while I have it in front of me. This was implemented by @douggie  a while back for both getOrderBook and getTrades:

https://github.com/knowm/XChange/commit/50e6d07d4007ba283a2348a9aa22fb2e0b096d44#diff-642258c03453c2d3c80e007847a1555eR46

I suggest closing this issue.

**Comment by ThomasWick** [comment]
@wvr I think it would be prudent to keep this issue open until the bug is fixed, @douggie 's implementation results in the error I mention above for getOrderBook by default unless checking for additional args is implemented.
