### ISSUE TITLE
[dsx] WARN  DSXExchange:65 - An exception occurred while loading the metadata

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#2670]
Does anyone has the same problem? Here is the stacktrace:

2018-06-22 16:54:19 WARN  DSXExchange:65 - An exception occurred while loading the metadata
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:122)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:162)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
	at com.sun.proxy.$Proxy15.getInfo(Unknown Source)
	at org.knowm.xchange.dsx.service.DSXMarketDataServiceRaw.getDSXInfo(DSXMarketDataServiceRaw.java:76)
	at org.knowm.xchange.dsx.DSXExchange.remoteInit(DSXExchange.java:62)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:128)

**Comment by makarid** [comment]
At last i found the issue. You need to do the things that this link tells: 
https://stackoverflow.com/questions/42848047/how-to-add-unsupported-cipher-suitesnot-included-in-the-default-cipher-suites
I am closing the issue.
