### ISSUE TITLE
Instantiation performance issue and a sporadic issue with BITFINEX (nonce is too small)

### ISSUE THREAD

**Issue by jmcklondonuk** [knowm/XChange#2761]
Given a multithreaded project, I use xchange to:
1. check balances of 6 different exchange markets
2. measure the REST API lag one market at a time, every second check a different market

I've implemented 1 as:
Loop through 6 exchanges, instantiate xchange (applySpecification) and execute account -> get wallets

And 2 is implemented as:
quartz job: get System.currentTimeMillis(), xchange get Ticker, get System.currentTimeMillis()
execute one getTicker at a time, then switch the Market for next run

Now the issues:
1. BITFINEX getBalances sporadically fails ("nonce is too small")

2. The quartz job often throws "socket timeout" but my network is idle and the bandwith is 50Mbps (bidirectional)
2018-08-17 23:47:59.951 ERROR 10804 --- [eduler_Worker-2] quartz.MarketApiLagJob   : An error occurred while running xchange the ticker to measure API lag: 

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_91]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_91]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_91]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_91]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_91]
	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_91]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973) ~[na:1.8.0_91]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930) ~[na:1.8.0_91]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_91]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_91]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_91]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_91]
	at sun.net.www.MeteredStream.read(MeteredStream.java:134) ~[na:1.8.0_91]
	at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336) ~[na:1.8.0_91]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_91]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_91]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_91]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_91]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[na:1.8.0_91]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[na:1.8.0_91]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[na:1.8.0_91]
	at si.mazi.rescu.HttpTemplate.readInputStreamAsEncodedString(HttpTemplate.java:231) ~[rescu-2.0.2.jar:na]
	at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:134) ~[rescu-2.0.2.jar:na]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:162) ~[rescu-2.0.2.jar:na]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119) ~[rescu-2.0.2.jar:na]
	at com.sun.proxy.$Proxy190.getTicker(Unknown Source) ~[na:na]
	at org.knowm.xchange.bitstamp.service.BitstampMarketDataServiceRaw.getBitstampTicker(BitstampMarketDataServiceRaw.java:32) ~[xchange-bitstamp-4.3.3.jar:na]
	at org.knowm.xchange.bitstamp.service.BitstampMarketDataService.getTicker(BitstampMarketDataService.java:24) ~[xchange-bitstamp-4.3.3.jar:na]

The project has multiple threads from where it instantiates and uses xchange. Are there any rules I need to abide to avoid these issues?

Instantiation performance: xchange instantiation is very slow. I've disabled the remote init and it is still considerably slow (applyExchangeSpecification processes metadata slowly from a json file because fasterxml parses too slowly). Hence, I'm planning to use an instance pool to cache xchange for every market. Getting an instance from the pool is immediate, while calling applyExchangeSpecification is slow.

Are there any recommendations for using xchange in a trading project? The project needs to send requests quickly without any "nonce is too small" issues or socket timeouts.

**Comment by walec51** [comment]
1) Is you server clocked synced via NTP?
2) Read timed outs mostly occur because the exchanges servers are overloaded and fail to generate a response in a timely matter

**Comment by garciapd** [comment]
@jmcklondonuk for the problem num 1. If you have more that one instance of the Exchange using the same API Key, it will fail, as every instance of that exchange is using its own NonceFactory. The nonce sent to Bitfinex has to be strictly incrementally, and if you have several instances each one will increment the number on its own and they won't be consecutive.
