### ISSUE TITLE
Bitmex - Explicit NullPointerException

### ISSUE THREAD

**Issue by w0lph** [knowm/XChange#2852]
There is an explicit NullPointerException on https://github.com/knowm/XChange/blob/develop/xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexAdapters.java#L327:34

**Comment by loftiestLoki** [comment]
NullPointerException also in Bitmexbaseservice when getting rate limit responses

**Comment by loftiestLoki** [comment]
Exception in thread "main" java.lang.NullPointerException
at org.knowm.xchange.bitmex.service.BitmexBaseService.updateRateLimit(BitmexBaseService.java:80)
at org.knowm.xchange.bitmex.service.BitmexMarketDataServiceRaw.getActiveTickers(BitmexMarketDataServiceRaw.java:65)
at org.knowm.xchange.bitmex.BitmexExchange.remoteInit(BitmexExchange.java:75)
at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115)
at org.knowm.xchange.bitmex.BitmexExchange.applySpecification(BitmexExchange.java:37)
at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:78)
at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:36)
at playPen.NonStreamExchange.main(NonStreamExchange.java:21)

The code I've used is:
`public static void main(String[] args) throws IOException {

Exchange bitstamp = ExchangeFactory.INSTANCE.createExchange(BitmexExchange.class.getName());

MarketDataService marketDataService = bitstamp.getMarketDataService();

Ticker ticker = marketDataService.getTicker(CurrencyPair.BTC_USD);

System.out.println(ticker.toString());
}
