### ISSUE TITLE
Bitmex RESTAPI headers bug

### ISSUE THREAD

**Issue by loftiestLoki** [knowm/XChange#2877]
Hi everyone,

I've been trying to connect to Bitmex but keep getting the following error:

Exception in thread "main" java.lang.NullPointerException
	at org.knowm.xchange.bitmex.service.BitmexBaseService.updateRateLimit(BitmexBaseService.java:80)
	at org.knowm.xchange.bitmex.service.BitmexMarketDataServiceRaw.getActiveTickers(BitmexMarketDataServiceRaw.java:65)
	at org.knowm.xchange.bitmex.BitmexExchange.remoteInit(BitmexExchange.java:75)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115)
	at org.knowm.xchange.bitmex.BitmexExchange.applySpecification(BitmexExchange.java:37)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:78)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:36)
	at playPen.NonStreamExchange.main(NonStreamExchange.java:21)

The code I've used is:
`public static void main(String[] args) throws IOException {

Exchange bitstamp = ExchangeFactory.INSTANCE.createExchange(BitmexExchange.class.getName());

MarketDataService marketDataService = bitstamp.getMarketDataService();

Ticker ticker = marketDataService.getTicker(CurrencyPair.BTC_USD);

System.out.println(ticker.toString());
}

`

Also, I tried using the code from the bitmex examples but still get the same error messages.

I had no problems with kraken, coinbase or poloniex so what am I doing wrong here with Bitmex?

**Comment by timmolter** [comment]
I think [this](https://github.com/knowm/XChange/pull/2879/files) fixes it. ??
