### ISSUE TITLE
[bit-z] Doesn't work

### ISSUE THREAD

**Issue by szd116** [knowm/XChange#2890]
When I try to query market data from bit-z I received the following error, please can someone help? Thanks.

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<!DOCTYPE html><html lang="zh"><head><script type="text/javascript">(function(para) {      var p = para.sdk_url, n = para.name, w = window, d = document, s = 'script',x = null,y = null;      w['sensorsDataAnalytic201505'] = n;      w[n] = w[n] || function(a) {return function() {(w[n]._q = w[n]._q || []).push([a, arguments]);}};      var ifs = ['track','quick','register','registerPage','registerOnce','trackSignup', 'trackAbtest', 'setProfile','setOnceProfile','appendProfile', 'incrementProfile', "[truncated 12116 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1892)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4130)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3030)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:65)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
	at com.sun.proxy.$Proxy10.getTickerResult(Unknown Source)
	at org.knowm.xchange.bitz.service.BitZMarketDataServiceRaw.getBitZTicker(BitZMarketDataServiceRaw.java:33)
	at org.knowm.xchange.bitz.service.BitZMarketDataService.getTicker(BitZMarketDataService.java:26)

**Comment by walec51** [comment]
cause of the problem: https://github.com/knowm/XChange/issues/2878 ?

**Comment by szd116** [comment]
Yes, it looks like the same issue, i have tried to fix it myself but to no avail.
