### ISSUE TITLE
Coinbene unexpected end of file from server 

### ISSUE THREAD

**Issue by szd116** [knowm/XChange#2928]
hello everyone,
is there someone else also getting the following errors, i was only trying to pull the order book, any ideas guys ?

java.net.SocketException: Unexpected end of file from server
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:862)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
        at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:122)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:162)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
        at com.sun.proxy.$Proxy41.orderBook(Unknown Source)
        at org.knowm.xchange.coinbene.service.CoinbeneMarketDataServiceRaw.getCoinbeneOrderBook(CoinbeneMarketDataServiceRaw.java:37)
        at org.knowm.xchange.coinbene.service.CoinbeneMarketDataService.getOrderBook(CoinbeneMarketDataService.java:45)
        at MarketdataBridge.run(MarketdataBridge.java:32)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by jakubkalicki** [comment]
What currency pair did you try to get? Please, paste exact line of code.

**Comment by szd116** [comment]
Hi there, thank you for getting back to me. the currencyPair that i'm trying to pull is CurrencyPair.ETH_BTC, please see the following code:

ExchangeSpecification coinBeneSpec = new ExchangeSpecification(CoinbeneExchange.class);
coinBeneSpec.setApiKey(API_KEY);
coinBeneSpec.setSecretKey(SECRET_KEY);
coinBeneSpec.setShouldLoadRemoteMetaData(false);
CoinbeneExchange coinBene =(CoinbeneExchange)ExchangeFactory.INSTANCE.createExchange(coinBeneSpec);

System.out.println(coinBene.getMarketDataService().getOrderBook(CurrencyPair.ETH_BTC));

**Comment by jakubkalicki** [comment]
This type of error could for example occur due to:
- lost network connection
- server closed the connection

Wrong credentials can't be the reason for closing connection in this case, because order book request uses public API (authentication is not needed). I tested exactly the same code as you did (with random credentials and without any) and it worked correctly.

Other idea is that maybe you are making many request in a loop. If you do, then note that Coinbene has following restriction:
"For every IP, API's access limit is 200times/10s."

**Comment by szd116** [comment]
Thank you again for all the help. The problem seems to be resolved, I think i might have hit their api rate limit. Thanks again for your time.
