### ISSUE TITLE
[Kucoin] NoSuchMethod error on Kucoin SDK

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#2977]
java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458)
	at com.kucoin.sdk.factory.RetrofitFactory.getPublicRetorfit(RetrofitFactory.java:33)
	at com.kucoin.sdk.rest.impl.retrofit.PublicRetrofitAPIImpl.getAPIImpl(PublicRetrofitAPIImpl.java:28)
	at com.kucoin.sdk.rest.adapter.SymbolAPIAdaptor.getSymbols(SymbolAPIAdaptor.java:27)
	at org.knowm.xchange.kucoin.KucoinMarketDataServiceRaw.lambda$getKucoinSymbols$2(KucoinMarketDataServiceRaw.java:31)
	at org.knowm.xchange.kucoin.KucoinExceptionClassifier.classifyingExceptions(KucoinExceptionClassifier.java:17)
	at org.knowm.xchange.kucoin.KucoinMarketDataServiceRaw.getKucoinSymbols(KucoinMarketDataServiceRaw.java:31)
	at org.knowm.xchange.kucoin.KucoinExchange.remoteInit(KucoinExchange.java:72)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115)
	at org.knowm.xchange.kucoin.KucoinExchange.applySpecification(KucoinExchange.java:39)

**Comment by badgerwithagun** [comment]
Hmm, strange. I'll try to replicate this.

**Comment by badgerwithagun** [comment]
I need to remove the dependence on the external SDK anyway, so may just go down that route if the cause isn't obvious.

**Comment by badgerwithagun** [comment]
@trixprod, I just did the following:

* Pulled the latest code on the `develop` branch
* Opened xchange-examples in my IDE
* Fully refreshed all Maven dependencies
* Ran `org.knowm.xchange.examples.kucoin.marketdata.KucoinMarketDataDemo`

Everything worked fine.

Can you post some code that causes this error?

**Comment by badgerwithagun** [comment]
Could you also check which version of okhttp3 you have on your classpath?

**Comment by trixprod** [comment]
I will try with the SDKless version and update the ticker status in few days.

**Comment by trixprod** [comment]
> Could you also check which version of okhttp3 you have on your classpath?

My okhttp3 version is 3.8.1
