### ISSUE TITLE
[Coinbase Pro] Issue on getTrades method

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#3007]
stack_trace: si.mazi.rescu.HttpStatusIOException: Conflicting property-based creators: already had implicitly discovered creator [constructor for org.knowm.xchange.coinbasepro.dto.marketdata.CoinbaseProTrade, annotations: [null]], encountered another: [constructor for org.knowm.xchange.coinbasepro.dto.marketdata.CoinbaseProTrade, annotations: [null]]
 at [Source: (String)"[{"time":"2019-03-18T17:26:33.242Z","trade_id":18311691,"price":"3506.43000000","size":"0.13541072","side":"buy"},{"time":"2019-03-18T17:26:33.242Z","trade_id":18311690,"price":"3506.45000000","size":"0.00100000","side":"buy"},{"time":"2019-03-18T17:26:29.436Z","trade_id":18311689,"price":"3506.46000000","size":"0.03030000","side":"sell"},{"time":"2019-03-18T17:26:28.778Z","trade_id":18311688,"price":"3506.48000000","size":"0.01805692","side":"buy"},{"time":"2019-03-18T17:26:24.186Z","trade_id":"[truncated 10852 chars]; line: 1, column: 1]
        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
        at com.sun.proxy.$Proxy247.getTrades(Unknown Source)
        at org.knowm.xchange.coinbasepro.service.CoinbaseProMarketDataServiceRaw.getCoinbaseProTrades(CoinbaseProMarketDataServiceRaw.java:93)

**Comment by trixprod** [comment]
It's due to double constructors in CoinbaseProTrade


```
    public CoinbaseProTrade(@JsonProperty("time") String timestamp, @JsonProperty("trade_id") long tradeId, @JsonProperty("price") BigDecimal price, @JsonProperty("size") BigDecimal size, @JsonProperty("side") String side) {
        this.timestamp = timestamp;
        this.tradeId = tradeId;
        this.price = price;
        this.size = size;
        this.side = side;
    }

    public CoinbaseProTrade(@JsonProperty("time") String timestamp, @JsonProperty("trade_id") long tradeId, @JsonProperty("price") BigDecimal price, @JsonProperty("size") BigDecimal size, @JsonProperty("side") String side, @JsonProperty("makerOrderId") String makerOrderId, @JsonProperty("takerOrderId") String takerOrderId) {
        this.timestamp = timestamp;
        this.tradeId = tradeId;
        this.price = price;
        this.size = size;
        this.side = side;
        this.makerOrderId = makerOrderId;
        this.takerOrderId = takerOrderId;
    }
```

**Comment by trixprod** [comment]
Related to commit 
https://github.com/knowm/XChange/commit/117528979067f45accb9f6fce2630648cb91bf80#diff-e271bdb9480e878f07dc03603f7d70d1

@makarid, can you check this please ? The constructeur renaming made a Json parsing confusion.

**Comment by makarid** [comment]
Hello @trixprod , i will check it now.

**Comment by trixprod** [comment]
@makarid 
I created a pull request to remove one constructor.
https://github.com/knowm/XChange/issues/3007

**Comment by trixprod** [comment]
Bug fixed by @makarid pull request.
So i close.
