### ISSUE TITLE
coinmarketcap API returns a warning

### ISSUE THREAD

**Issue by willll** [knowm/XChange#3024]
Hi, I have the following warning when I createExchange a coinmarketcap :

**WARN org.knowm.xchange.coinmarketcap.pro.v1.CmcExchange - An exception occured while loading the metadata file from the file system. This is just a warning and can be ignored, but it may lead to unexpected results, so it's better to address it.
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]**
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2796)
	at org.knowm.xchange.BaseExchange.loadMetaData(BaseExchange.java:141)
	at org.knowm.xchange.BaseExchange.loadExchangeMetaData(BaseExchange.java:132)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:100)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:78)
[... my code ...]

Did I forgot to integrate something ? I am using 4.3.16.

**Comment by jakubkalicki** [comment]
Hey,

It's not something that you should worry about, but i can get rid of that warning.
Please paste exact code that you used, so i can reproduce this issue.

**Comment by walec51** [comment]
closing due to lack of response
