### ISSUE TITLE
[Kucoin] Error 401 on getTradeHistory call

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#3036]
stack_trace: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 401
        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
        at com.sun.proxy.$Proxy262.queryTrades(Unknown Source)
        at org.knowm.xchange.kucoin.KucoinTradeServiceRaw.lambda$getKucoinFills$1(KucoinTradeServiceRaw.java:44)
        at org.knowm.xchange.kucoin.KucoinExceptionClassifier.classifyingExceptions(KucoinExceptionClassifier.java:17)
        at org.knowm.xchange.kucoin.KucoinTradeServiceRaw.getKucoinFills(KucoinTradeServiceRaw.java:42)
        at org.knowm.xchange.kucoin.KucoinTradeService.getTradeHistory(KucoinTradeService.java:68)

**Comment by trixprod** [comment]
Not relevant, got my API deleted i don't know why and error 401 should not happen here.
