### ISSUE TITLE
Coinbase Pro Sandbox Invalid API Key

### ISSUE THREAD

**Issue by masterofcoin** [knowm/XChange#3063]
I get an Invalid API Key when using an API Key for the coinbase pro sandbox. api-public.sandbox.pro.coinbase.com

I have triple verified the API key parameters and the same code works on the api.pro.coinbase.com endpoint. 

Code: 
        ExchangeSpecification exSpec = new 
        CoinbaseProExchange().getDefaultExchangeSpecification();
        exSpec.setHost("api-public.sandbox.pro.coinbase.com");
        exSpec.setExchangeSpecificParametersItem("passphrase", *passphrase*);
        exSpec.setApiKey(*key*);
        exSpec.setSecretKey(*secret*);
        exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);

        // Get the account information
        accountService = exchange.getAccountService();
        accountInfo = accountService.getAccountInfo();

Stack trace:

org.knowm.xchange.coinbasepro.dto.CoinbaseProException: Invalid API Key (HTTP status code: 400)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:189)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:421)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3030)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
	at com.sun.proxy.$Proxy10.getAccounts(Unknown Source)
	at org.knowm.xchange.coinbasepro.service.CoinbaseProAccountServiceRaw.getCoinbaseProAccountInfo(CoinbaseProAccountServiceRaw.java:34)
	at org.knowm.xchange.coinbasepro.service.CoinbaseProAccountService.getAccountInfo(CoinbaseProAccountService.java:37)

**Comment by jakubkalicki** [comment]
Try like this:

`Exchange exchange = ExchangeFactory.INSTANCE.createExchangeWithoutSpecification(CmcExchange.class);
ExchangeSpecification spec = ((CmcExchange) exchange).getSandboxExchangeSpecification();
spec.setApiKey("yourApiKey");
spec.setSecretKey("yourSecretKey");
exchange.applySpecification(spec);`

**Comment by amjad1210** [comment]
```
    @Override
    protected ExchangeSpecification getDefaultSpecification(ExchangeSpecification exSpec) {
        exSpec.setApiKey("apiKey");
        exSpec.setSecretKey("secretKey");
        exSpec.setExchangeSpecificParametersItem("passphrase", "password");
        exSpec.setExchangeSpecificParametersItem("Use_Sandbox", true);
        return exSpec;
    }
```

**Comment by masterofcoin** [comment]
Thanks for the responses. This means I have to redesign my code for test cases. I'll give it a try when I do.
