### ISSUE TITLE
the demo for okex is incorrect

### ISSUE THREAD

**Issue by rzyaly** [knowm/XChange#3082]
Exchange okcoinExchange =
                ExchangeFactory.INSTANCE.createExchange(OkCoinExchange.class.getName());

        ExchangeSpecification exchangeSpecification = new ExchangeSpecification(okcoinExchange.getClass());
        exchangeSpecification.setSslUri("https://www.okex.com/api");
        exchangeSpecification.setHost("www.okex.com");
       exchangeSpecification.setExchangeName("OKEX");
        exchangeSpecification.setApiKey("***");
        exchangeSpecification.setSecretKey("***");
        exchangeSpecification.setExchangeDescription("OKEX is a globally oriented crypto-currency trading platform.");
        exchangeSpecification.setProxyHost("127.0.0.1");
        exchangeSpecification.setProxyPort(10818);
        exchangeSpecification.setExchangeSpecificParametersItem("tradepwd","***");
        exchangeSpecification.setExchangeSpecificParametersItem("Use_Intl", true);
        exchangeSpecification.setExchangeSpecificParametersItem("Use_Futures", false);
        okcoinExchange.applySpecification(exchangeSpecification);
        System.out.println(JsonUtil.toJson(okcoinExchange.getAccountService().getAccountInfo()));

Am I missing something ?  - -
And the error return message is 
Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: Signature does not match
	at org.knowm.xchange.okcoin.service.OKCoinBaseTradeService.returnOrThrow(OKCoinBaseTradeService.java:42)
	at org.knowm.xchange.okcoin.service.OkCoinAccountServiceRaw.getUserInfo(OkCoinAccountServiceRaw.java:39)
	at org.knowm.xchange.okcoin.service.OkCoinAccountService.getAccountInfo(OkCoinAccountService.java:44)
	at Main.main(Main.java:34)

**Comment by rzyaly** [comment]
this is v3 api key .. i am sorry
