### ISSUE TITLE
NPE on BinanceExchange remoteInit call

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#3108]
Hello, do you have this issue with Binance too ?
```

stack_trace: java.lang.NullPointerException: null
        at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:124)
        ... 6 common frames omitted
Wrapped by: org.knowm.xchange.exceptions.ExchangeException: Failed to initialize: null
        at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:142)
        at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115)
        at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:128)
        at com.trixprod.crypto.xchange.market.service.worker.ExchangeWorker.run(ExchangeWorker.java:95)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by cymp** [comment]
See https://github.com/knowm/XChange/pull/3071, https://github.com/knowm/XChange/pull/3099 and https://github.com/knowm/XChange/pull/3100.

**Comment by trixprod** [comment]
That's ok now. I close
