### ISSUE TITLE
[Kucoin] Error 400 on KucoinMarketDataService.getTrades call

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#3110]
stack_trace: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 400
        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
        at com.sun.proxy.$Proxy265.getTradeHistories(Unknown Source)
        at org.knowm.xchange.kucoin.KucoinMarketDataServiceRaw.lambda$getKucoinTrades$4(KucoinMarketDataServiceRaw.java:50)
        at org.knowm.xchange.kucoin.KucoinExceptionClassifier.classifyingExceptions(KucoinExceptionClassifier.java:17)
        at org.knowm.xchange.kucoin.KucoinMarketDataServiceRaw.getKucoinTrades(KucoinMarketDataServiceRaw.java:49)
        at org.knowm.xchange.kucoin.KucoinMarketDataService.getTrades(KucoinMarketDataService.java:47)

**Comment by trixprod** [comment]
Only happen on not provided currency pair ( like RHOC/ETH). I clode

**Comment by cymp** [comment]
Well in this case maybe add a thrown exception in the case the pair is not provided, what do you think?
