### ISSUE TITLE
[Bitmex] AccountService null pointer - updateRateLimit

### ISSUE THREAD

**Issue by rastooo** [knowm/XChange#3133]
xchange-bitmex-4.3.20
xchange-core-4.3.20

I get a null pointer exception when getting accountInfo. Code used:
        AccountService accountService = exchange.getAccountService();
        AccountInfo accountInfo = accountService.getAccountInfo();

Exception in thread "main" java.lang.NullPointerException
	at org.knowm.xchange.bitmex.service.BitmexBaseService.updateRateLimit(BitmexBaseService.java:104)
	at org.knowm.xchange.bitmex.service.BitmexAccountServiceRaw.getBitmexAccountInfo(BitmexAccountServiceRaw.java:30)
	at org.knowm.xchange.bitmex.service.BitmexAccountService.getAccountInfo(BitmexAccountService.java:40)

**Comment by rastooo** [comment]
I got rid of the exception by catching it in BitmexBaseService.updateRateLimit(). It is not a very systematic solution. But will do for now. The next issue that followed is an invalid signature. I will close this issue and open another one.
