### ISSUE TITLE
[Bitmex] Signature not valid

### ISSUE THREAD

**Issue by rastooo** [knowm/XChange#3145]
I get a signature not valid from Bitmex. API keys are valid. Has anyone come across this error?
My code:
        ExchangeSpecification bitmexSpec = new BitmexExchange().getDefaultExchangeSpecification();        
        bitmexSpec.setApiKey("..");
        bitmexSpec.setSecretKey("..");
        bitmexSpec.setUserName("...");
        bitmexSpec.setHost("bitmex.com");
        bitmexSpec.setSslUri("https://www.bitmex.com");
        Exchange exchange = ExchangeFactory.INSTANCE.createExchange(bitmexSpec);

        AccountService accountService = exchange.getAccountService();
        AccountInfo accountInfo = accountService.getAccountInfo();

Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: Signature not valid. (HTTP:  401).
	at org.knowm.xchange.bitmex.service.BitmexBaseService.handleError(BitmexBaseService.java:57)
	at org.knowm.xchange.bitmex.service.BitmexBaseService.updateRateLimit(BitmexBaseService.java:102)
	at org.knowm.xchange.bitmex.service.BitmexAccountServiceRaw.getBitmexAccountInfo(BitmexAccountServiceRaw.java:30)
	at org.knowm.xchange.bitmex.service.BitmexAccountService.getAccountInfo(BitmexAccountService.java:40)

**Comment by rastooo** [comment]
The signature was calculated incorrectly. There was a redundant /. I created a pull request. This also solved the Rate-Limit issue that I mentioned previously.
