### ISSUE TITLE
BinanceException on BinanceAccountServiceRaw.withdrawHistory call

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#3184]
```
Params :
org.knowm.xchange.binance.service.BinanceFundingHistoryParams@76b26972[currency=SKY,type=<null>,startTime=Thu Jan 01 00:00:00 UTC 1970,endTime=Sat Aug 24 08:39:08 UTC 2019])

Exception :
stack_trace: org.knowm.xchange.binance.dto.BinanceException: null
        at sun.reflect.GeneratedConstructorAccessor195.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
        at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
        at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
        at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
        at com.sun.proxy.$Proxy286.withdrawHistory(Unknown Source)
        at org.knowm.xchange.binance.service.BinanceAccountServiceRaw.withdrawHistory(BinanceAccountServiceRaw.java:116)
        at org.knowm.xchange.binance.service.BinanceAccountService.getFundingHistory(BinanceAccountService.java:214)
        ... 7 common frames omitted
Wrapped by: org.knowm.xchange.exceptions.ExchangeException: Operation failed without any error message
        at org.knowm.xchange.binance.BinanceErrorAdapter.adapt(BinanceErrorAdapter.java:45)
        at org.knowm.xchange.binance.service.BinanceAccountService.getFundingHistory(BinanceAccountService.java:256)
```

This call was working few weeks ago. ( with same params ).
I will also investigate, if you have got the same issue, please tell me.

Regards

**Comment by walec51** [comment]
turn on HTTP tracing in logs: https://github.com/knowm/XChange/wiki/New-Implementation-Best-Practices#step-3

we'll see how binance responded to your request

**Comment by trixprod** [comment]
2019-08-24 12:54:26.783  INFO 21428 --- [ool-10-thread-1] si.mazi.rescu.ResponseReader             : Constructed an exception with no message. Response body was: {"withdrawList":[],"success":true}

Hmm response body seems to be correct.

**Comment by walec51** [comment]
msg will be just null then I think

paste the full log and stacktrace here, the cause of the problem is ad the end of the stacktrace

**Comment by trixprod** [comment]
![BinanceException](https://user-images.githubusercontent.com/12997320/63655249-244bc000-c786-11e9-87f8-199e7f474bb7.png)

It really looks like to a Jackson construction error.

**Comment by walec51** [comment]
I've just added an integration test and tested it with a real account:

https://github.com/knowm/XChange/pull/3198/files#diff-9a53d125fa09b4e7b1a4e19b8d2de0e5R92

there was no problem with withdrawals

if you cannot provide me the FULL log with TRACE enabled so I can see both the request and the response then I cannot help you

**Comment by trixprod** [comment]
Hello, thank you for your answer @walec51 .
I can't reproduce with the last SNAPSHOT, so i close for the moment.
