### ISSUE TITLE
error when creating bitfinex exchange with key and secret key

### ISSUE THREAD

**Issue by googya** [knowm/XChange#3205]
```shell
[2019-09-06 18:59:41:829] WARN [arbitrageAkkaSystem-akka.actor.default-dispatcher-4] (si.mazi.rescu.ResponseReader:) - Noncritical error parsing error output: [["tBTCUSD",10754,65.66836384,10755,57.0289385,96.1529242,0.009,10754.1529242,4164.80988527,10800,10490],["tLTCUSD",67.46,1472.6022711199998,67.526,2031.4371211799998,1.396,0.0211,67.478,75728.9856219...
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.knowm.xchange.bitfinex.dto.BitfinexException out of START_ARRAY token
 at [Source: java.io.StringReader@3f4b9613; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1378) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:174) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880) ~[jackson-databind-2.8.7.jar:2.8.7]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53) ~[rescu-2.0.2.jar:?]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58) ~[rescu-2.0.2.jar:?]
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82) [rescu-2.0.2.jar:?]
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175) [rescu-2.0.2.jar:?]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163) [rescu-2.0.2.jar:?]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119) [rescu-2.0.2.jar:?]
	at com.sun.proxy.$Proxy130.getTickers(Unknown Source) [?:?]
	at org.knowm.xchange.bitfinex.service.BitfinexMarketDataServiceRaw.getBitfinexTickers(BitfinexMarketDataServiceRaw.java:94) [xchange-bitfinex-4.3.21.jar:?]
	at org.knowm.xchange.bitfinex.BitfinexExchange.remoteInit(BitfinexExchange.java:71) [xchange-bitfinex-4.3.21.jar:?]
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115) [xchange-core-4.3.21.jar:?]
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:128) [xchange-core-4.3.21.jar:?]
	at com.exchange.market.maker.service.ExchangeUtils.findXchangeByNameWithSec(ExchangeUtils.java:53) [classes/:?]
	at com.exchange.market.maker.akka.actor.BalanceUpdateActor.process(BalanceUpdateActor.java:45) [classes/:?]
	at com.exchange.market.maker.akka.actor.BalanceUpdateActor.onReceive(BalanceUpdateActor.java:31) [classes/:?]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) [akka-actor_2.11-2.3.12.jar:?]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) [akka-actor_2.11-2.3.12.jar:?]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) [akka-actor_2.11-2.3.12.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:?]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:?]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.5.jar:?]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.5.jar:?]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.5.jar:?]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.5.jar:?]
org.knowm.xchange.exceptions.ExchangeException: si.mazi.rescu.HttpStatusIOException: Unexpected token (VALUE_NUMBER_FLOAT), expected END_ARRAY: Unexpected JSON values; expected at most 11 properties (in JSON Array)
 at [Source: java.io.StringReader@78fd16ce; line: 1, column: 46332] (through reference chain: java.lang.Object[][417])
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:117)

```

.xchange.bitfinex.BitfinexExchange:) - Calling Remote Init...
[2019-09-07 10:11:32:209] WARN [arbitrageAkkaSystem-akka.actor.default-dispatcher-5] (si.mazi.rescu.ResponseReader:) - Noncritical error parsing error output: [["tBTCUSD",10362,50.61192774,10363,48.37204804,-270,-0.0254,10363,11369.905834,10933,10208],["tLTCUSD",65.053,1502.5849301500002,65.054,1762.36194516,-0.768,-0.0117,65.053,66325.23598725,68.134,63.9]...
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.knowm.xchange.bitfinex.dto.BitfinexException out of START_ARRAY token

**Comment by googya** [comment]
the code is 

```java

        ExchangeSpecification exSpec;
        switch (config.getName()) {
            case EXCHANGE_NAME.BINANCE:
                exSpec = new BinanceExchange().getDefaultExchangeSpecification();
                break;
            case EXCHANGE_NAME.HUOBI:
                exSpec = new HuobiExchange().getDefaultExchangeSpecification();
                break;
            case EXCHANGE_NAME.KRAKEN:
                exSpec = new KrakenExchange().getDefaultExchangeSpecification();
                break;
            case EXCHANGE_NAME.BITSTAMP:
                exSpec = new BitstampExchange().getDefaultExchangeSpecification();
                break;
            case EXCHANGE_NAME.BITFINEX:
                exSpec = new BitfinexExchange().getDefaultExchangeSpecification();
                break;
            default: throw new RuntimeException("no support " + config.getName());
        }
        exSpec.setUserName(config.getUsername());
        exSpec.setApiKey(config.getAppKey());
        exSpec.setSecretKey(config.getAppSercret());

        return ExchangeFactory.INSTANCE.createExchange(exSpec);

```

**Comment by googya** [comment]
now, i have a demo to reproduce:

```java
import com.alibaba.fastjson.JSON;
import org.knowm.xchange.Exchange;
import org.knowm.xchange.ExchangeFactory;
import org.knowm.xchange.ExchangeSpecification;
import org.knowm.xchange.bitfinex.BitfinexExchange;
import org.knowm.xchange.bitfinex.service.BitfinexAccountService;
import org.knowm.xchange.bitfinex.service.BitfinexTradeService;
import org.knowm.xchange.bitfinex.v1.dto.account.BitfinexBalancesResponse;
import org.knowm.xchange.bitfinex.v1.dto.trade.BitfinexActivePositionsResponse;
import org.knowm.xchange.dto.account.AccountInfo;
import org.knowm.xchange.dto.trade.OpenOrders;

import java.io.BufferedReader;
import java.io.InputStreamReader;

public class BitfinexDemo {
    public static void main(String[] args)  throws Exception {
        ExchangeSpecification exSpec = new BitfinexExchange().getDefaultExchangeSpecification();
        String apiKey = "";
        String secretKey = "";

        try {
            System.out.print("API Key: ");
            System.out.flush();
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            apiKey = br.readLine();

            System.out.print("Secret Key: ");
            System.out.flush();
            secretKey = br.readLine();
        } catch (Exception e) {
            System.out.println("error" + e.getMessage());
        }

        exSpec.setApiKey(apiKey);
        exSpec.setSecretKey(secretKey);
        Exchange bitfinex = ExchangeFactory.INSTANCE.createExchange(exSpec);

        // Get the account information
        BitfinexAccountService accountService = new BitfinexAccountService(bitfinex);

        BitfinexTradeService bitfinexTradeService = new BitfinexTradeService(bitfinex);
        AccountInfo accountInfo = accountService.getAccountInfo();
        System.out.println(accountInfo.toString());

        BitfinexBalancesResponse[] bitfinexAccountInfo = accountService.getBitfinexAccountInfo();
        System.out.println(JSON.toJSONString(bitfinexAccountInfo));

        OpenOrders openOrders = bitfinexTradeService.getOpenOrders();
        System.out.println(JSON.toJSONString(openOrders));

        BitfinexActivePositionsResponse[] bitfinexActivePositions = bitfinexTradeService.getBitfinexActivePositions();
        System.out.println(JSON.toJSONString(bitfinexActivePositions));
    }
}

```

and the error is the same:

```shell

[2019-09-07 10:17:55:582] INFO [main] (org.knowm.xchange.bitfinex.BitfinexExchange:) - Calling Remote Init...
Exception in thread "main" [2019-09-07 10:17:57:546] WARN [main] (si.mazi.rescu.ResponseReader:) - Noncritical error parsing error output: [["tBTCUSD",10367,50.040042250000006,10369,70.18758309,-281,-0.0264,10369,11327.38230428,10933,10208],["tLTCUSD",65.053,1604.3267894800001,65.054,1630.5893697899999,-0.819,-0.0124,65.002,66325.2859872...
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.knowm.xchange.bitfinex.dto.BitfinexException out of START_ARRAY token
 at [Source: java.io.StringReader@379614be; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1378) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:174) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150) ~[jackson-databind-2.8.7.jar:2.8.7]
org.knowm.xchange.exceptions.ExchangeException: si.mazi.rescu.HttpStatusIOException: Unexpected token (VALUE_NUMBER_FLOAT), expected END_ARRAY: Unexpected JSON values; expected at most 11 properties (in JSON Array)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[jackson-databind-2.8.7.jar:2.8.7]
 at [Source: java.io.StringReader@55c53a33; line: 1, column: 46663] (through reference chain: java.lang.Object[][417])
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880) ~[jackson-databind-2.8.7.jar:2.8.7]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53) ~[rescu-2.0.2.jar:?]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58) ~[rescu-2.0.2.jar:?]
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82) [rescu-2.0.2.jar:?]
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175) [rescu-2.0.2.jar:?]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163) [rescu-2.0.2.jar:?]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119) [rescu-2.0.2.jar:?]
	at com.sun.proxy.$Proxy31.getTickers(Unknown Source) [?:?]
	at org.knowm.xchange.bitfinex.service.BitfinexMarketDataServiceRaw.getBitfinexTickers(BitfinexMarketDataServiceRaw.java:94) [xchange-bitfinex-4.3.21.jar:?]
	at org.knowm.xchange.bitfinex.BitfinexExchange.remoteInit(BitfinexExchange.java:71) [xchange-bitfinex-4.3.21.jar:?]
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115) [xchange-core-4.3.21.jar:?]
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:128) [xchange-core-4.3.21.jar:?]
	at BitfinexDemo.main(BitfinexDemo.java:43) [test-classes/:?]
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:117)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:128)

```

**Comment by timmolter** [comment]
What's at line 43 in your code?

**Comment by googya** [comment]
after upgrading SpringBoot to latest version,  the errors are gone. so, it is not the problem of Xchange.
