### ISSUE TITLE
version 4.4.0 OkexAccountService.getAccountInfo() error

### ISSUE THREAD

**Issue by suihs11** [knowm/XChange#3226]
version 4.4.0 OkexAccountService.getAccountInfo() throws an Exception
ExceptionMessage: duplicate wallets passed to AccountInfo

**Comment by makarid** [comment]
With just getAccountInfo() method or with getAccountInfo().getWallet();

**Comment by walec51** [comment]
full stack trace pls

**Comment by sizmestiev** [comment]
Suppose the issue is in the copy+paste error: two `Wallet.WalletFeature.FUNDING` usages instead of `FUNDING`/`TRADING`.

https://github.com/knowm/XChange/blob/5b79b8ff103bc39622e7ee79260077520063770d/xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexAccountService.java#L58

https://github.com/knowm/XChange/blob/5b79b8ff103bc39622e7ee79260077520063770d/xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexAccountService.java#L61

**Comment by makarid** [comment]
Yes it is

**Comment by suihs11** [comment]
The full stack trace:

java.lang.IllegalArgumentException: duplicate wallets passed to AccountInfo
	at org.knowm.xchange.dto.account.AccountInfo.<init>(AccountInfo.java:104)
	at org.knowm.xchange.dto.account.AccountInfo.<init>(AccountInfo.java:77)
	at org.knowm.xchange.dto.account.AccountInfo.<init>(AccountInfo.java:114)
	at org.knowm.xchange.dto.account.AccountInfo.<init>(AccountInfo.java:40)
	at org.knowm.xchange.okcoin.v3.service.OkexAccountService.getAccountInfo(OkexAccountService.java:62)
	at io.renren.modules.exchangeApi.service.impl.ExchangeApiServiceImpl.callExchangeCash(ExchangeApiServiceImpl.java:115)
	at io.renren.modules.exchangeApi.task.CollectMethod.doTask1(CollectMethod.java:89)
	at io.renren.modules.exchangeApi.task.CollectMethod$$FastClassBySpringCGLIB$$ef5d846.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Exception At org.knowm.xchange.dto.account.AccountInfo.java  Line 103 wallet.getId() = null  twice;





To fix this exception with:
At org.knowm.xchange.okcoin.v3.service.OkexAccountService.java Line 56:
return new AccountInfo(
        Wallet.Builder.from(fundingBalances)
            .id("Funding")
            .features(Stream.of(Wallet.WalletFeature.FUNDING).collect(Collectors.toSet()))
            .build(),
        Wallet.Builder.from(tradingBalances)
            .id("Trading")
            .features(Stream.of(Wallet.WalletFeature.TRADING).collect(Collectors.toSet()))
            .build()

**Comment by suihs11** [comment]
@walec51

**Comment by walec51** [comment]
@makarid 
this is a bug due to your change: https://github.com/knowm/XChange/commit/4fbf21c83effd8f02fc7a6c869fda52be1751cc8#diff-21fc4054389a06d0460febe25d402492
fix it pls as @suihs11

**Comment by walec51** [comment]
fixed
