### ISSUE TITLE
[bitfinex] Error createExchange

### ISSUE THREAD

**Issue by tiagoferraro** [knowm/XChange#3246]
line where the error is triggered
        exchange = ExchangeFactory.INSTANCE.createExchange( BitfinexExchange::class.java.name,APIKEY,SECRET)

Log error 
W/System.err: org.knowm.xchange.exceptions.ExchangeException: si.mazi.rescu.HttpStatusIOException: Cannot deserialize value of type `java.math.BigDecimal` from String "tBTCUSD": not a valid representation
        at [Source: (StringReader); line: 1, column: 3] (through reference chain: java.lang.Object[][0]->org.knowm.xchange.bitfinex.v2.dto.marketdata.BitfinexTicker["ask"])
W/System.err:     at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:117)
        at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:78)

**Comment by walec51** [comment]
just merged a PR that might help, please build the latest snapshot on your machine and test against it

**Comment by walec51** [comment]
closing due to lack of response

**Comment by GusWard** [comment]
I am still getting this issue on Android, seems to be attempting to parse the 'symbol' as a BigDecimal. Could this be something to do with a mismatched parsing library?

**Comment by msgilligan** [comment]
I'm seeing this issue on Android, too. (Using `minSdkVersion 28` and `targetSdkVersion 29`)

**Comment by veken0m** [comment]
I get the same issue on Android.

@GusWard Are you able to clean up your pull request so that it can be merged? The @JsonPropertyOrder fix resolves the issue because for some reason Android deserializes the properties in alphabetical order by default.

**Comment by walec51** [comment]
I'm wondering does this library even work on Android after we moved to Java 11?
