### ISSUE TITLE
CampBX calls failing

### ISSUE THREAD

**Issue by jpe42** [knowm/XChange#339]
It is because of the new DDoS protection they added.  I believe someone like @mmazi  would already know the solution to this... let me know and I will follow up with CampBX to see what parameters we should include.

Logged call from demo's:

```
09:15:19.140 [default] [main] DEBUG
                si.mazi.rescu.HttpTemplate - Executing POST request at https://campbx.com/api/xticker.php 
09:15:19.141 [default] [main] TRACE
                si.mazi.rescu.HttpTemplate - Request body =  
09:15:19.141 [default] [main] TRACE
                si.mazi.rescu.HttpTemplate - Request headers = {} 
09:15:19.333 [default] [main] TRACE
                si.mazi.rescu.HttpTemplate - Header request property: key='Accept-Charset', value='UTF-8' 
09:15:19.334 [default] [main] TRACE
                si.mazi.rescu.HttpTemplate - Header request property: key='User-Agent', value='ResCU JDK/6 AppleWebKit/535.7 Chrome/16.0.912.36 Safari/535.7' 
09:15:19.334 [default] [main] TRACE
                si.mazi.rescu.HttpTemplate - Header request property: key='Content-Type', value='application/x-www-form-urlencoded' 
09:15:19.334 [default] [main] TRACE
                si.mazi.rescu.HttpTemplate - Header request property: key='Accept', value='application/json' 
09:15:19.852 [default] [main] DEBUG
                si.mazi.rescu.HttpTemplate - Request http status = 503 
Exception in thread "main" java.io.IOException: HTTP status code was 503; response body: <!DOCTYPE HTML><html lang="en-US"><head>  <meta charset="UTF-8" />  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />  <meta name="robots" content="noindex, nofollow" />  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />  <title>Just a moment...</title>  <style type="text/css">    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}    h1 {font-size: 1.5em; color: #404040; text-align: center;}    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}    #spinner {margin: 0 auto 30px auto; display: block;}    .attribution {margin-top: 20px;}  </style>  <script type="text/javascript">  //<![CDATA[  (function(){    var onReady = function( callback ){        var addListener = document.addEventListener || document.attachEvent,            eventName = document.addEventListener ? 'DOMContentLoaded' : 'onreadystatechange';        addListener.call(document, eventName, function(){ callback(); }, false );    }    onReady(function(){      var content = document.getElementById('cf-content');      content.style.display = 'block';      setTimeout(function(){        var t,r,a,f;        t = document.createElement('div');        t.innerHTML="<a href='/'>x</a>";        t = t.firstChild.href;        r = t.match(/https?:\/\//)[0];        t = t.substr(r.length);        t = t.substr(0,t.length-1);        a = document.getElementById('jschl-answer');        f = document.getElementById('challenge-form');        a.value = 35+10*8;        a.value = parseInt(a.value, 10) + t.length;        f.submit();      }, 5850);    });  })();  //]]></script></head><body>  <table width="100%" height="100%" cellpadding="20">    <tr>      <td align="center" valign="middle">          <div class="cf-browser-verification cf-im-under-attack">  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>  <div id="cf-content" style="display:none">    <img id="spinner" src="/cdn-cgi/images/spinner-2013.gif" />    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> campbx.com.</h1>    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>  </div>  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">    <input type="hidden" name="jschl_vc" value="eb0e3491e29fc8ead6ba91cb2845c0f7"/>    <input type="hidden" id="jschl-answer" name="jschl_answer"/>  </form></div>          <div class="attribution"><a href="http://www.cloudflare.com/" target="_blank" style="font-size: 12px;">DDoS protection by CloudFlare</a></div>      </td>    </tr>  </table></body></html>
    at si.mazi.rescu.HttpTemplate.executeRequest(HttpTemplate.java:132)
    at si.mazi.rescu.RestInvocationHandler.invokeHttp(RestInvocationHandler.java:66)
    at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:51)
    at com.sun.proxy.$Proxy10.getTicker(Unknown Source)
    at com.xeiam.xchange.campbx.service.polling.CampBXMarketDataServiceRaw.getCampBXTicker(CampBXMarketDataServiceRaw.java:60)
    at com.xeiam.xchange.campbx.service.polling.CampBXMarketDataService.getTicker(CampBXMarketDataService.java:55)
    at com.xeiam.xchange.examples.campbx.marketdata.CampBXMarketDataDemo.generic(CampBXMarketDataDemo.java:56)
    at com.xeiam.xchange.examples.campbx.marketdata.CampBXMarketDataDemo.main(CampBXMarketDataDemo.java:46)
```

Edited: log formatting

**Comment by bryan4887** [comment]
I'm getting the same CloudFare protection things right now with btc-e and Kraken. This could be because I poll very frequently, but I now see what these 503s are about that I occasionally get:
```
Exception in thread "main" si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 503
        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:106)
        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:137)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:125)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:104)
        at com.sun.proxy.$Proxy10.getAssetPairs(Unknown Source)
        at com.xeiam.xchange.kraken.service.polling.KrakenBasePollingService.getKrakenAssetPairs(KrakenBasePollingService.java:136)
        at com.xeiam.xchange.kraken.service.polling.KrakenBasePollingService.getExchangeSymbols(KrakenBasePollingService.java:63)
```

Does anyone know a way around this other than to poll less frequently?

**Comment by rafalkrupinski** [comment]
How often do you poll? BTC-e caches public data for 2 seconds and I never had any problems with it.

**Comment by bryan4887** [comment]
@rafalkrupinski that's right, I forgot that about BTC-e, but Kraken doesn't cache every two seconds...
@mmazi You think it's possible to catch and process these CloudFare checks (Something more specific than a 503) and then use your Retries class to automatically back off on the polling?  That would be a decently robust way to handle it without changing too much.

**Comment by mmazi** [comment]
@bryan4887 I'm not sure how to go about detecting that a 503 is a CloudFare check failure. It would probably entail a custom Json deserializer that could detect that the returned body is not actually json, and would also check its contents for something like 'www.cloudflare.com' and report this appropriately.

**Comment by bryan4887** [comment]
OK—I suppose this will have to be something to revisit in the future if necessary.
