### ISSUE TITLE
[KRAKEN] incorrect ZERO check in KrakenAccountService::getAccountInfo()

### ISSUE THREAD

**Issue by sizmestiev** [knowm/XChange#3475]
Zero-check fix is incorrect and leads to java.lang.ArithmeticException: Division undefined

```
java.lang.ArithmeticException: Division undefined
    at java.math.BigDecimal.divide(BigDecimal.java:1744)
    at org.knowm.xchange.kraken.service.KrakenAccountService.getAccountInfo(KrakenAccountService.java:53)
```

Current fix: https://github.com/knowm/XChange/commit/cd06a9a195c641615548c71cbe92832ae20855c8

Explanation:
https://stackoverflow.com/questions/10950914/how-to-check-if-bigdecimal-variable-0-in-java

**Comment by sizmestiev** [comment]
@makarid

**Comment by makarid** [comment]
Hello, did i create this bug?

**Comment by makarid** [comment]
As i see, this happens when the account has zero funds in it. It is an easy fix can you please make this PR because right now i don't have the time to do it?

**Comment by sizmestiev** [comment]
@makarid Sorry, wrong commit link. Right is:
https://github.com/knowm/XChange/commit/4544e972e8a660dd71931fe1f6598a0150317441#diff-a69d46b8f4687e2f9cef8dd26f194d84

**Comment by makarid** [comment]
> @makarid Sorry, wrong commit link. Right is:
> [4544e97#diff-a69d46b8f4687e2f9cef8dd26f194d84](https://github.com/knowm/XChange/commit/4544e972e8a660dd71931fe1f6598a0150317441#diff-a69d46b8f4687e2f9cef8dd26f194d84)

OK, i forgot to put the check to currentLeverage field.

**Comment by sizmestiev** [comment]
> 
> So, you fix it?

Not yet, seems like issue is not urgent. Will do PR little bit later.

**Comment by makarid** [comment]
> > So, you fix it?
> 
> Not yet, seems like issue is not urgent. Will do PR little bit later.

Great, thanks!

**Comment by sizmestiev** [comment]
@makarid I'm not familiar with github and known/XChange PR procedure. Did I submit PR correctly?

**Comment by makarid** [comment]
yes you need to make a pull request to the original repository

**Comment by sizmestiev** [comment]
> yes you need to make a pull request to the original repository

Thanks, got it!
