### ISSUE TITLE
Idex Unreconginzed field "slug"

### ISSUE THREAD

**Issue by gulteking** [knowm/XChange#3530]
When i tried to call getExchangeMetaData() metadata or getExchangeSymbols(), application throws exception below.

I found the cause, while getting metadata, It calls "https://api.idex.market/returnCurrencies" from IdexMarketDataService. Response contains `"slug"` filed, but assigned dto(`ReturnCurrenciesResponse`) not contains slug value. Because of this, we are getting error. 
to solve error, just need to ignore unknown fields while creating objectMapper. 

```
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        return objectMapper.readerFor(ReturnCurrenciesResponse.class).readValue(inputStreamReader);
```

I will solve create a pull request for this soon.

Exception stacktrace: 

`com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "slug" (class org.knowm.xchange.idex.dto.IdexCurrMeta), not marked as ignorable (3 known properties: "decimals", "name", "address"])
 at [Source: (InputStreamReader); line: 1, column: 194] (through reference chain: org.knowm.xchange.idex.dto.ReturnCurrenciesResponse["PLU"]->org.knowm.xchange.idex.dto.IdexCurrMeta["slug"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:843)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1244)
	at org.knowm.xchange.idex.IdexMarketDataService$Companion.allCurrenciesStatic(IdexMarketDataService.java:242)
	at org.knowm.xchange.idex.IdexExchange.getExchangeMetaData(IdexExchange.java:44)`

**Comment by earce** [comment]
Is there a motivation for ignoring the "slug" field instead of adding it to the `IdexCurrMeta` object to deserialize?

**Comment by badgerwithagun** [comment]
`FAIL_ON_UNKNOWN_PROPERTIES` s is used as a default throughout the streaming code for this reason. Exchanges are always adding new properties. That could be what happened here.

**Comment by walec51** [comment]
@gulteking thank you for the fix, just change the test class name and as @badgerwithagun suggested and will merge it

ps. be advised that that our idex module is really badly written and I intend to rewrite it in the following weeks

**Comment by earce** [comment]
Looks like this ticket can be closed?
