### ISSUE TITLE
[Bitmex] NullPointerException in create when there are unlisted assets

### ISSUE THREAD

**Issue by phraktle** [knowm/XChange#3556]
xchange is unable to initialize with BitMEX when there are unlisted (new but not yet tradeable quarterly futures added), as is currently the case (see [announcement here](https://blog.bitmex.com/q3-2020-quarterly-futures-listings/))

At the moment, the following is sufficient to reproduce the issue:
```
import org.knowm.xchange.ExchangeFactory;
import org.knowm.xchange.bitmex.BitmexExchange;

public class BMTest {

    public static void main(String[] args) {
        var spec = new BitmexExchange().getDefaultExchangeSpecification();
        ExchangeFactory.INSTANCE.createExchange(spec);        
    }

}
```

Which throws the following NPE, since it expects the assets to have a price available, which they do not have in this case.

```
11:40:37.066 [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating exchange from specification
11:40:37.069 [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name
11:40:37.069 [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name
11:40:37.506 [main] DEBUG org.knowm.xchange.bitmex.BitmexExchange - ExchangeMetaData [currencyPairs={XBT/USD=CurrencyPairMetaData [tradingFee=null, minimumAmount=1, maximumAmount=null, baseScale=null, priceScale=1, amountStepSize=null, tradingFeeCurrency=null], ETH/USD=CurrencyPairMetaData [tradingFee=null, minimumAmount=1, maximumAmount=null, baseScale=null, priceScale=2, amountStepSize=null, tradingFeeCurrency=null]}, currencies={XBT=CurrencyMetaData [scale=null, withdrawalFee=0, minWithdrawalAmount=null, walletHealth=null], XRP=CurrencyMetaData [scale=null, withdrawalFee=null, minWithdrawalAmount=null, walletHealth=null], BCH=CurrencyMetaData [scale=null, withdrawalFee=null, minWithdrawalAmount=null, walletHealth=null], ADA=CurrencyMetaData [scale=null, withdrawalFee=null, minWithdrawalAmount=null, walletHealth=null], EOS=CurrencyMetaData [scale=null, withdrawalFee=null, minWithdrawalAmount=null, walletHealth=null], TRX=CurrencyMetaData [scale=null, withdrawalFee=null, minWithdrawalAmount=null, walletHealth=null], ETH=CurrencyMetaData [scale=null, withdrawalFee=null, minWithdrawalAmount=null, walletHealth=null], LTC=CurrencyMetaData [scale=null, withdrawalFee=null, minWithdrawalAmount=null, walletHealth=null], USD=CurrencyMetaData [scale=null, withdrawalFee=null, minWithdrawalAmount=null, walletHealth=null]}, publicRateLimits=[RateLimit [calls=150, timeSpan=300, timeUnit=SECONDS]], privateRateLimits=[RateLimit [calls=300, timeSpan=300, timeUnit=SECONDS]], shareRateLimits=true]
11:40:37.521 [main] DEBUG si.mazi.rescu.Config - Configuration from rescu.properties:
11:40:37.521 [main] DEBUG si.mazi.rescu.Config - httpConnTimeout = 30000
11:40:37.523 [main] DEBUG si.mazi.rescu.Config - httpReadTimeout = 30000
11:40:37.523 [main] DEBUG si.mazi.rescu.Config - proxyHost = null
11:40:37.523 [main] DEBUG si.mazi.rescu.Config - proxyPort = null
11:40:37.523 [main] DEBUG si.mazi.rescu.Config - ignoreHttpErrorCodes = false
11:40:37.559 [main] INFO org.knowm.xchange.bitmex.BitmexExchange - Calling Remote Init...
11:40:37.570 [main] DEBUG si.mazi.rescu.HttpTemplate - Executing GET request at https://www.bitmex.com/api/v1/instrument/active
11:40:38.462 [main] DEBUG si.mazi.rescu.HttpTemplate - Request http status = 200
Exception in thread "main" java.lang.NullPointerException
	at org.knowm.xchange.bitmex.BitmexExchange.lambda$getPriceScale$3(BitmexExchange.java:153)
	at java.base/java.util.Optional.map(Optional.java:258)
	at org.knowm.xchange.bitmex.BitmexExchange.getPriceScale(BitmexExchange.java:153)
	at org.knowm.xchange.bitmex.BitmexExchange.lambda$updateExchangeMetaData$1(BitmexExchange.java:116)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.knowm.xchange.bitmex.BitmexExchange.updateExchangeMetaData(BitmexExchange.java:110)
	at org.knowm.xchange.bitmex.BitmexExchange.remoteInit(BitmexExchange.java:79)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:107)
	at org.knowm.xchange.bitmex.BitmexExchange.applySpecification(BitmexExchange.java:43)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:128)
	at BMTest.main(BMTest.java:15)

```

**Comment by phraktle** [comment]
Setting `spec.setShouldLoadRemoteMetaData(false)` is a workaround for this problem (as long as one is only trading the assets listed in the default metadata).

**Comment by cbeaujoin** [comment]
Hi,
same kind of issue here due to BCH/USD symbol that has no last price.
Thank you for the workaround it works fine.

Something has to be done in BitmexExchange class and more specifically getPriceScale method
`        .map(ticker -> ticker.getLastPrice().scale())` that is not NPE proof.

**Comment by earce** [comment]
We should be ok to close this.
