### ISSUE TITLE
Kraken Error - EGeneral:Internal error

### ISSUE THREAD

**Issue by spikeruk** [knowm/XChange#3570]
Any idea why I would get the below error?

nested exception is org.knowm.xchange.exceptions.ExchangeException: [EGeneral:Internal error]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at com.r307.arbitrader.Arbitrader.main(Arbitrader.java:11)
Caused by: org.knowm.xchange.exceptions.ExchangeException: [EGeneral:Internal error]
        at org.knowm.xchange.kraken.service.KrakenBaseService.checkResult(KrakenBaseService.java:93)
        at org.knowm.xchange.kraken.service.KrakenAccountServiceRaw.getKrakenTradeBalance(KrakenAccountServiceRaw.java:148)
        at org.knowm.xchange.kraken.service.KrakenAccountServiceRaw.getKrakenTradeBalance(KrakenAccountServiceRaw.java:159)
        at org.knowm.xchange.kraken.service.KrakenAccountService.getAccountInfo(KrakenAccountService.java:40)

Its a new Kraken account, with no funds

**Comment by earce** [comment]
@spikeruk is this an issue you get continuously or it happened a single time?

**Comment by dazito** [comment]
I am also getting this exact same exception on a new account with no funds - like the OP.
