### ISSUE TITLE
[CoinbasePro] NPE en getHeader method ( "cb-after" is in lowercase but "Cb-After" is in the header )

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#3579]
`stack_trace: java.lang.NullPointerException: null
        at org.knowm.xchange.coinbasepro.dto.CoinbaseProTransfers.getHeader(CoinbaseProTransfers.java:24)
        at org.knowm.xchange.coinbasepro.service.CoinbaseProAccountService.getFundingHistory(CoinbaseProAccountService.java:179)
`

The NPE happen here :
        createdAt = transfers.getHeader("cb-after"); << The header contains Cb-After

![image](https://user-images.githubusercontent.com/12997320/86185718-4dbc4180-bb37-11ea-8c80-e8e3a7d20305.png)

**Comment by mattpeacock** [comment]
This issue was affecting me too. I have raised a PR for this https://github.com/knowm/XChange/pull/3582

**Comment by earce** [comment]
Looks like  this ticket can be closed as well?
