### ISSUE TITLE
[Kraken] Futures Contract breaks

### ISSUE THREAD

**Issue by mdvx** [knowm/XChange#3664]
`java.lang.IllegalStateException: The instrument of this order is not a currency pair: null
	at org.knowm.xchange.dto.Order.getCurrencyPair(Order.java:233)
	at info.bitrich.xchangestream.kraken.KrakenStreamingTradeService.lambda$getOrderChanges$2(KrakenStreamingTradeService.java:93)
`
KrakenStreamingTradeService.getOrderChanges(CurrencyPair....)

temp fix
` return Observable.create(
          emit ->
              ownTradesObservable
                  .filter(
                      order -> {
                        if (order.getInstrument() instanceof CurrencyPair)
                          return ((CurrencyPair) order.getInstrument()).compareTo(currencyPair)
                              == 0;

                        if (order.getInstrument() instanceof FuturesContract)
                          return ((FuturesContract) order.getInstrument())
                                  .getCurrencyPair()
                                  .compareTo(currencyPair)
                              == 0;

                        return false;
                      })
                  .subscribe(emit::onNext, emit::onError, emit::onComplete));
`
@makarid @badgerwithagun

**Comment by mdvx** [comment]
we probably need to upgrade getOrderChanges to use Instrument and provide a way to compare currrencyPair and FuturesContract?

**Comment by mdvx** [comment]
This seems out of data
