### ISSUE TITLE
BTCMarketsException Authentication failed for marketOrder only.

### ISSUE THREAD

**Issue by zdary** [knowm/XChange#3689]
BTCMarket fails with authentication error for marketOrder. It however, works fine for other services, i.e. order books.

```
4015:org.knowm.xchange.btcmarkets.dto.BTCMarketsException: Authentication failed.:  (HTTP status code: 200)
4016-	at jdk.internal.reflect.GeneratedConstructorAccessor203.newInstance(Unknown Source)
4017-	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
4018-	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
4019-	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
4020-	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
4021-	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
4022-	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
4023-	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:490)
4024-	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
4025-	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
4026-	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
4027-	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
4028-	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
4029-	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
4030-	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
4031-	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
4032-	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
4033-	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
4034-	at com.sun.proxy.$Proxy178.placeOrder(Unknown Source)
4035-	at org.knowm.xchange.btcmarkets.service.BTCMarketsTradeServiceRaw.placeBTCMarketsOrder(BTCMarketsTradeServiceRaw.java:39)
4036-	at org.knowm.xchange.btcmarkets.service.BTCMarketsTradeService.placeOrder(BTCMarketsTradeService.java:73)
4037-	at org.knowm.xchange.btcmarkets.service.BTCMarketsTradeService.placeMarketOrder(BTCMarketsTradeService.java:45)
```

**Comment by nielsdraaisma** [comment]
hi @zdary, this will most likely be resolved by https://github.com/knowm/XChange/pull/3688 .

**Comment by zdary** [comment]
awesome, thank you :)

**Comment by zdary** [comment]
@nielsdraaisma nice effort, I think you need to run to source code formatting before submission too
