### ISSUE TITLE
Kraken - Invalid Key when fetching deposit address

### ISSUE THREAD

**Issue by zdary** [knowm/XChange#3698]
Invalid Key when fetching deposit address.
The key is ok for other operations.

```
org.knowm.xchange.exceptions.ExchangeException: [EAPI:Invalid key]] with root cause
org.knowm.xchange.exceptions.ExchangeException: [EAPI:Invalid key]
	at org.knowm.xchange.kraken.service.KrakenBaseService.checkResult(KrakenBaseService.java:96)
	at org.knowm.xchange.kraken.service.KrakenAccountServiceRaw.getDepositAddresses(KrakenAccountServiceRaw.java:57)
	at org.knowm.xchange.kraken.service.KrakenAccountService.requestDepositAddress(KrakenAccountService.java:85)
```

**Comment by earce** [comment]
This seems like a kraken specific issue? Is your key intended for read only?
