### ISSUE TITLE
NoClassDefFoundError when creating poloniex exchange

### ISSUE THREAD

**Issue by ufotje** [knowm/XChange#3715]
Anyone else experiencing this error when creating a poloniex exchange through the factory method?:
Caused by: java.lang.NoClassDefFoundError: org/knowm/xchange/client/ClientConfigCustomizer
	at org.knowm.xchange.poloniex.service.PoloniexBaseService.<init>(PoloniexBaseService.java:34) ~[classes/:na]
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataServiceRaw.<init>(PoloniexMarketDataServiceRaw.java:35) ~[classes/:na]
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataService.<init>(PoloniexMarketDataService.java:34) ~[classes/:na]
	at org.knowm.xchange.poloniex.PoloniexExchange.initServices(PoloniexExchange.java:24) ~[classes/:na]
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:102) ~[xchange-core-5.0.2.jar:na]
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:78) ~[xchange-core-5.0.2.jar:na]
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:36) ~[xchange-core-5.0.2.jar:na]
	at net.goanation.services.poloniex.PoloniexInfoService.<init>(PoloniexInfoService.java:19) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.knowm.xchange.client.ClientConfigCustomizer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
	... 38 common frames omitted

I'm sure all the dependecies are on the classpath, so I guess it has to do with the static initiliazer block, but have no idea how to fix it. Any ideas

**Comment by walec51** [comment]
are all your XChange dependencies in the same version?

**Comment by walec51** [comment]
closing because of no reply
