### ISSUE TITLE
Better Errorhandling

### ISSUE THREAD

**Issue by ufotje** [knowm/XChange#3744]
When the serever returns a 400 statuscode, you shouldn't try to bind the result to an object:
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'error': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"error code: 1015"; line: 1, column: 6]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:717) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2898) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1944) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:776) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4662) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4511) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466) ~[jackson-databind-2.11.2.jar:2.11.2]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53) ~[rescu-2.0.2.jar:na]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58) ~[rescu-2.0.2.jar:na]
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82) ~[rescu-2.0.2.jar:na]
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175) ~[rescu-2.0.2.jar:na]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163) ~[rescu-2.0.2.jar:na]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119) ~[rescu-2.0.2.jar:na]
	at com.sun.proxy.$Proxy111.getMarketTicker(Unknown Source) ~[na:na]
	at org.knowm.xchange.bankera.service.BankeraMarketDataServiceRaw.getBankeraTicker(BankeraMarketDataServiceRaw.java:22) ~[xchange-bankera-5.0.2.jar:na]
	at org.knowm.xchange.bankera.service.BankeraMarketDataService.getTicker(BankeraMarketDataService.java:23) ~[xchange-bankera-5.0.2.jar:na]
	at me.sideways8.cabbi.services.bankera.BankeraInfoService.getTickerForPair(BankeraInfoService.java:30) ~[classes/:na]
	at me.sideways8.cabbi.controllers.ParibuController.getExchangeData(ParibuController.java:97) ~[classes/:na]
	at me.sideways8.cabbi.controllers.KucoinController.getTickers(KucoinController.java:83) ~[classes/:na]
	at me.sideways8.cabbi.controllers.KucoinController.lambda$arbitrage$0(KucoinController.java:65) ~[classes/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-10-05 14:56:57.784  WARN 10308 --- [ol-305-thread-1] si.mazi.rescu.ResponseReader             : Noncritical error parsing error output: error code: 1015

**Comment by timmolter** [comment]
@mmazi Is there a mechanism in rescu for this??

**Comment by mmazi** [comment]
If I understand correctly, the server returns a different json structure with status 200 than with other statuses? Then the simplest way to cover this is to declare the service method with `throws MyException` where `MyException extends HttpStatusExceptionSupport`.  See [a test example](https://github.com/mmazi/rescu/blob/4623119a9f7c2fc344863638fa25d81ec65c2bbd/src/test/java/si/mazi/rescu/ExampleService.java#L59) and [ExampleExeption](https://github.com/mmazi/rescu/blob/4623119a9f7c2fc344863638fa25d81ec65c2bbd/src/test/java/si/mazi/rescu/ExampleException.java). There are also many examples of this in XChange.

**Comment by ufotje** [comment]
No, it dosn't, I feel like the statuscode isn't being checked at all, so when the statuscode is 400 it still tries to bind the json to the object resulting in this error

**Comment by walec51** [comment]
@ufotje we have a special object to parses error responses:
https://github.com/knowm/XChange/blob/658a9e26ec829608e6c01c80c75eaecb473abad4/xchange-bankera/src/main/java/org/knowm/xchange/bankera/dto/BankeraException.java#L6

the  problem is not that we should not deserialize the error response
the problem seams to be that the exchange returned some strange error response that we did not anticipate

cloud your log what the exchange is returning?

you can to with wireshark or by increasing the logging level of mazi

**Comment by mmazi** [comment]
@ufotje rescu *does* check for HTTP status code. I think you misunderstood what I wrote - by 'server' I meant the Bankera API server.

@walec51 According to the stack trace you are right.

To see the exact response body returned by the API server you can increase the logging level in `logback.xml`:

         <logger name="si.mazi.rescu" level="trace"/>

From the error message `Unrecognized token 'error': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')` it seems to me that the server returns something that is not JSON. I think it simply returns "error code: 1015" (see the stack trace), which is not json. 

To fix the issue you should probably remove `BankeraException` from the method `trows` clause; either replace it with `HttpStatusExceptionSupport` or only leave `IOException` and see what happens.

The problem is that the API server returns a different Content-Type for different status codes (JSON for 200 and text for 400) which rescu doesn't support. The method must be declared with `@Produces(MediaType.APPLICATION_JSON)` so that the 200 response gets parsed correctly, but then the text/plain (400) response doesn't get parsed correctly.

Perhaps it's OK even the way it is now as the actual error message "error code: 1015" *is* included in the exception thrown, it's just a bit harder to find. See if you like it more with the `throws` clause changes suggested above.

**Comment by walec51** [comment]
@ufotje could you increase you logging level as @mmazi described and paste your request and response here?

**Comment by walec51** [comment]
closing due to lack of response
