### ISSUE TITLE
xhchange-binance 2 tests fail 

### ISSUE THREAD

**Issue by jurepetrovic** [knowm/XChange#3808]
Gentlemen, 

I am getting error on mvn package comman in develop branch. 
Any ideas what that might be? Using openjdk-15.0.

```
[ERROR] Process Exit Code: 0
k[ERROR] Crashed tests:
H[ERROR] org.knowm.xchange.binance.service.marketdata.MarketDataServiceResilienceTest
a[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
n[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-15.0.1\bin\java" -jar C:\Users\jure\AppData\Local\Temp\surefire3344733857606590647\surefirebooter3653959665010758778.jar C:\Users\jure\AppData\Local\Temp\surefire3344733857606590647 2020-11-13T10-17-02_441-jvmRun1 surefire9671589161351467059tmp surefire_02054377321870306343tmp"
d[ERROR] Process Exit Code: 0
l[ERROR] Crashed tests:
e[ERROR] org.knowm.xchange.binance.service.marketdata.MarketDataServiceResilienceTest
r[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
D[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
i[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
s[ERROR]        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
p[ERROR]        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
a[ERROR]        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
t[ERROR]        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137) c[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
h[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
i[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
n[ERROR]        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
g[ERROR]        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
S[ERROR]        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
e[ERROR]        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
r[ERROR]        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
v[ERROR]        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
l[ERROR]        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
e[ERROR]        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
t[ERROR]        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
,[ERROR]        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
j[ERROR]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
s[ERROR]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
p[ERROR]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
=[ERROR]        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
n[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
u[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
l[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
l[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
,[ERROR]
o[ERROR] -> [Help 1]
```

**Comment by jurepetrovic** [comment]
Ok, I checked it further yesterday and 2 tests in binance package fail like described above. 
Did anyone else have the same issue with develop branch?

**Comment by walec51** [comment]
two questions:
- did you `mvn install` the xchange-core module from develop as well?
- do you have the same problem when using openjdk 11?

**Comment by jurepetrovic** [comment]
- I did mvn install in the main xchange.git folder. It stopped on resilience tests in binance folder. 

- before that I used version xchange-stream 4.4.1-snapshot, which was not merged yet. from info.bitrich repository. Complement with that was java se 8, directly from oracle, so that was quiet a leap for me

-  to make it work, i removed the 2 offending tests and it seems to run fine. I suppose you're having completely no troubles with binance tests in develop branch? What maven version are you using?

**Comment by walec51** [comment]
do you have the same problem when using openjdk 11?

**Comment by gewure** [comment]
Binance fails for me aswell.

**Comment by walec51** [comment]
closing due to lack of response

**Comment by jurepetrovic** [comment]
Sorry, did not try the openjdk-11. 
I just removed the tests, temporarily "mitigating" the issue.
Everything else worked fine. 

Will try again, when I have some other work on that part of the 
code again.

Rgds, 
Jure
