### ISSUE TITLE
Streaming-Poloniex NullPointer and missing onError handler in subscribe()

### ISSUE THREAD

**Issue by gewure** [knowm/XChange#3843]
i get this frequently:

```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `info.bitrich.xchangestream.poloniex2.dto.PoloniexWebSocketEventsTransaction`, problem: `java.lang.NullPointerException`
 at [Source: UNKNOWN; line: -1, column: -1]

Caused by: java.lang.NullPointerException
	at info.bitrich.xchangestream.poloniex2.dto.PoloniexWebSocketEventsTransaction.createEvents(PoloniexWebSocketEventsTransaction.java:46)
	at info.bitrich.xchangestream.poloniex2.dto.PoloniexWebSocketEventsTransaction.<init>(PoloniexWebSocketEventsTransaction.java:28)
	at jdk.internal.reflect.GeneratedConstructorAccessor110.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
```

**Comment by gewure** [comment]
interestingly enough, streaming orderbooks still works in 90% of the cases im presented with this error in my app. im investigating this and maybe PR if i got a fix.

**Comment by earce** [comment]
Can you post the code for your subscription?

**Comment by gewure** [comment]
sure:

```
  Disposable sub = poloStreamExch.getStreamingMarketDataService()
                    .getOrderBook(this.pair)
                    .subscribe(orderBook -> {   .... }
```

sometimes it works and is just fine, sometimes it don't

**Comment by earce** [comment]
you need to have an "onError" or use the subscribe with an error parameter

**Comment by gewure** [comment]
> you need to have an "onError" or use the subscribe with an error parameter

Ok, thank you.

 but.. shouldn't that be caught by Streaming-Poloniex already?

**Comment by earce** [comment]
Has nothing to do with xchange, it's part of the expectation when using RX java. You as a subscriber need to handle the error cases. Think of using REST in exchange or anything with IO, you are expected to catch IO exceptions because different applications have different ways of handling those types of errors.

**Comment by earce** [comment]
User error
