### ISSUE TITLE
[Coinbase] 404 on getCoinbaseBuyPrice call

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#3902]
Hello, on calling org.knowm.xchange.coinbase.service.CoinbaseMarketDataServiceRaw.getCoinbaseBuyPrice(CoinbaseMarketDataServiceRaw.java:79) we have got a CoinbaseException ( 404 )

I've tested with an existing currency pair : BTC/EUR.

Here is the stack trace :

stack_trace: org.knowm.xchange.coinbase.dto.CoinbaseException: null (HTTP status code: 404)
        at jdk.internal.reflect.GeneratedConstructorAccessor185.newInstance(Unknown Source)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
        at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
        at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
        at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
        at com.sun.proxy.$Proxy303.getBuyPrice(Unknown Source)
        at org.knowm.xchange.coinbase.service.CoinbaseMarketDataServiceRaw.getCoinbaseBuyPrice(CoinbaseMarketDataServiceRaw.java:79)
        at org.knowm.xchange.coinbase.service.CoinbaseMarketDataService.getTicker(CoinbaseMarketDataService.java:42)

**Comment by Bad-Pop** [comment]
I'm in the same situation with this code :

```java
var coinbase =
        ExchangeFactory.INSTANCE.createExchange(
            CoinbaseExchange.class, "myApiKey", "mySecret");

var marketData = coinbase.getMarketDataService();

var test = marketData.getTicker(BTC_USD);
log.info("Data : {}", test);
```

And the execution result :

```
Caused by: org.knowm.xchange.coinbase.dto.CoinbaseException: null (HTTP status code: 404)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:490) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468) ~[jackson-databind-2.11.4.jar:2.11.4]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53) ~[rescu-2.0.4.jar:na]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58) ~[rescu-2.0.4.jar:na]
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82) ~[rescu-2.0.4.jar:na]
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:179) ~[rescu-2.0.4.jar:na]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:167) ~[rescu-2.0.4.jar:na]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:123) ~[rescu-2.0.4.jar:na]
	at com.sun.proxy.$Proxy123.getBuyPrice(Unknown Source) ~[na:na]
	at org.knowm.xchange.coinbase.service.CoinbaseMarketDataServiceRaw.getCoinbaseBuyPrice(CoinbaseMarketDataServiceRaw.java:79) ~[xchange-coinbase-5.0.6.jar:na]
	at org.knowm.xchange.coinbase.service.CoinbaseMarketDataService.getTicker(CoinbaseMarketDataService.java:42) ~[xchange-coinbase-5.0.6.jar:na]
	at com.github.badpop.cointoring.CointoringApplication.run(CointoringApplication.java:36) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[spring-boot-2.4.3.jar:2.4.3]
	... 10 common frames omitted
```

I have tested many other xchange's features with Coinbase and it seems that nothing works for me :'(

Can anyone help us ?

**Comment by pecpwee** [comment]
you need to import the  v2 version of CoinbaseExchange ( org.knowm.xchange.coinbase.v2.CoinbaseExchange ) to create the Exchage object.
the CoinbaseExchange of v1 had been abandoned
