### ISSUE TITLE
[BINANCE] Invalid symbol

### ISSUE THREAD

**Issue by AlexanderTrybushnyi** [knowm/XChange#3942]
public static void main(String[] args) throws IOException {
    ExchangeSpecification exSpec = new BinanceExchange().getDefaultExchangeSpecification();
    exSpec.setApiKey("myApiKey");
    exSpec.setSecretKey("mySecret");
    Exchange binance = ExchangeFactory.INSTANCE.createExchange(exSpec);
    MarketDataService marketDataService = binance.getMarketDataService();
    Ticker ticker = marketDataService.getTicker(CurrencyPair.EUR_USD);
    System.out.println(ticker.toString());
  }

Exception in thread "main" org.knowm.xchange.exceptions.CurrencyPairNotValidException: Invalid symbol. (HTTP status code: 400)
	at org.knowm.xchange.binance.BinanceErrorAdapter.adapt(BinanceErrorAdapter.java:45)
	at org.knowm.xchange.binance.service.BinanceMarketDataService.getTicker(BinanceMarketDataService.java:76)
	at Main.main(Main.java:19)

**Comment by earce** [comment]
I don't think EUR/USD is a valid binance pair?

**Comment by dpageau2021** [comment]
@earce are right, EUR/USD doesn't exist in Binance, you must use USDT (Theter) instead of USD
