### ISSUE TITLE
Connection timed out: connect Upbit Exchange

### ISSUE THREAD

**Issue by deniben** [knowm/XChange#3961]
```
(ExchangeUtils.java:33)
->    33 private Exchange upbit = ExchangeFactory.INSTANCE.createExchange(UpbitExchange.class);
```
```
02-Mar-2021 23:04:17.191 SEVERE [http-nio-8080-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke РћС€РёР±РєР° РІС‹РґРµР»РµРЅРёСЏ РґР»СЏ СЃРµСЂРІР»РµС‚Р° [dispatcher]
	java.net.ConnectException: Connection timed out: connect
		at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
		at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:81)
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
		at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
		at java.net.Socket.connect(Socket.java:606)
		at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:287)
		at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
		at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
		at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
		at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:292)
		at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:395)
		at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
		at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
		at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
		at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
		at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
		at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
		at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:145)
		at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:166)
		at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:123)
		at com.sun.proxy.$Proxy53.getMarketAll(Unknown Source)
--->	at org.knowm.xchange.upbit.service.UpbitMarketDataServiceRaw.getMarketAll(UpbitMarketDataServiceRaw.java:45)
--->	at org.knowm.xchange.upbit.service.UpbitMarketDataService.getMetaData(UpbitMarketDataService.java:52)**
--->	at org.knowm.xchange.upbit.UpbitExchange.remoteInit(UpbitExchange.java:34)**
		at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:113)
		at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:110)
		at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:53)
--->	at com.spring.trader.utils.ExchangeUtils.<init>(ExchangeUtils.java:33)
		at com.spring.trader.controller.BinanceController.<init>(BinanceController.java:27)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1224)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1131)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
		at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
		at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:676)
		at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:545)
		at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:499)
		at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:172)
		at javax.servlet.GenericServlet.init(GenericServlet.java:158)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:777)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by deniben** [comment]
I think it on working 
![image](https://user-images.githubusercontent.com/19304301/109716060-00eca700-7bad-11eb-97e1-723535f8c0cf.png)
