### ISSUE TITLE
Placing order for FuturesContract on Binance

### ISSUE THREAD

**Issue by jumpingfella** [knowm/XChange#3966]
Can't submit market order for futures contract, details below:
`
java.lang.IllegalStateException: The instrument of this order is not a currency pair: BTC/USDT/perpetual
	at org.knowm.xchange.dto.Order.getCurrencyPair(Order.java:238)
	at org.knowm.xchange.binance.service.BinanceTradeService.placeOrder(BinanceTradeService.java:147)
	at org.knowm.xchange.binance.service.BinanceTradeService.placeMarketOrder(BinanceTradeService.java:101)
`
https://github.com/knowm/XChange/blob/9fd9618faeac567a516e68ba6e7108d58bd1504f/xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeServiceRaw.java#L52

**Comment by BePe2** [comment]
I don't think it's possible to submit FutureContracts via BinanceTradeService atm
