### ISSUE TITLE
Binance invocationUrl is null

### ISSUE THREAD

**Issue by valentyn1789** [knowm/XChange#3987]
The problem came up this morning
It is not possible to create an BinanceExchange
![image](https://user-images.githubusercontent.com/79843713/112286418-f9905900-8c93-11eb-9fdf-0b4af82ccac6.png)

org.knowm.xchange.exceptions.ExchangeException: Failed to initialize: null

	at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:171)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:113)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:130)
	at com.crypto.demo.XchangeTest.test(XchangeTest.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.NullPointerException
	at org.knowm.xchange.binance.service.BinanceHmacDigest.digestParams(BinanceHmacDigest.java:81)
	at si.mazi.rescu.Params.digestAll(Params.java:203)
	at si.mazi.rescu.RestInvocation.digestAll(RestInvocation.java:152)
	at si.mazi.rescu.RestInvocation.<init>(RestInvocation.java:78)
	at si.mazi.rescu.RestInvocation.create(RestInvocation.java:127)
	at si.mazi.rescu.RestInvocationHandler.createInvocation(RestInvocationHandler.java:192)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy17.assetDetail(Unknown Source)
	at org.knowm.xchange.binance.service.BinanceAccountServiceRaw.lambda$requestAssetDetail$4(BinanceAccountServiceRaw.java:115)
	at org.knowm.xchange.client.ResilienceUtils$DecorateCallableApi.call(ResilienceUtils.java:90)
	at org.knowm.xchange.binance.service.BinanceAccountServiceRaw.requestAssetDetail(BinanceAccountServiceRaw.java:119)
	at org.knowm.xchange.binance.service.BinanceAccountService.getAssetDetails(BinanceAccountService.java:177)
	at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:101)
	... 25 more

**Comment by earce** [comment]
Associated with https://github.com/knowm/XChange/pull/3989

**Comment by tonykwok1992** [comment]
PR merge, can you test if it is fixed now?
