### ISSUE TITLE
build fails?

### ISSUE THREAD

**Issue by andrewyuyang** [knowm/XChange#4019]
Hi I have this problem ever since upgrading from 4.4.2. this line is causing it:
    static MarketDataService kucoinMarketDataService = ExchangeFactory.INSTANCE.createExchange(KucoinExchange.class).getMarketDataService();

it has the following messsages: 

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
2 actionable tasks: 2 executed
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Administrator/Desktop/bot/reactive-crypto.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Administrator/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Exception in thread "main" java.lang.IncompatibleClassChangeError: Class com.google.common.base.Suppliers$MemoizingSupplier does not implement the requested interface java.util.function.Supplier
	at org.knowm.xchange.interceptor.InterceptorProvider.provide(InterceptorProvider.java:22)
	at org.knowm.xchange.client.ExchangeRestProxyBuilder.forInterface(ExchangeRestProxyBuilder.java:37)
	at org.knowm.xchange.kucoin.KucoinBaseService.service(KucoinBaseService.java:61)
	at org.knowm.xchange.kucoin.KucoinBaseService.<init>(KucoinBaseService.java:41)
	at org.knowm.xchange.kucoin.KucoinMarketDataServiceRaw.<init>(KucoinMarketDataServiceRaw.java:20)
	at org.knowm.xchange.kucoin.KucoinMarketDataService.<init>(KucoinMarketDataService.java:23)
	at org.knowm.xchange.kucoin.KucoinExchange.initServices(KucoinExchange.java:48)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:108)
	at org.knowm.xchange.kucoin.KucoinExchange.applySpecification(KucoinExchange.java:41)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:80)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:38)
	at Main.<clinit>(Main.java:134)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Main.main()'.
> Process 'command 'C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2021.1/jbr/bin/java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by andrewyuyang** [comment]
The only thing I can think of is the use of static. But again this was not a problem before. If anyone can help, thanks in advance!

**Comment by timmolter** [comment]
it looks like you're trying to run it via gradle in intellij using the intellij jvm. Please try running it via maven from the command line using a Java JVM from adopt open jdk version 8 or higher.
