### ISSUE TITLE
[FTX][STREAM] UserTrade : NotYetImplementedForExchangeException

### ISSUE THREAD

**Issue by dgosset** [knowm/XChange#4041]
Hi,

I try to have realtime/websocket with FTX and a subaccount. 
I did something wrong? or this is not "Not Yet Implemented" for real?

Exception in thread "main" org.knowm.xchange.exceptions.NotYetImplementedForExchangeException: getStreamingTradeService
        at info.bitrich.xchangestream.core.StreamingExchange.getStreamingTradeService(StreamingExchange.java:115)
        at com.swtm.tradingbot.TradingBotApplication.main(TradingBotApplication.java:173)

If it is not yes implemented, is there a way to do something like that (to trigger an action, after a full filled order).

Thanks.

**Comment by dgosset** [comment]
Ok, i saw it is not implemented : FtxStreamingTradeService doesn't exist.

Any help to implement this? I try to find an example with auth. 

I coded a FtxStreamingTradeService.getUserTrades() with Auth (sign, etc.)
I started but i have a 

2021-04-30 13:23:56.339  INFO   --- [           main] i.b.x.ftx.FtxStreamingService            : Subscribing to channel fills:BTC/USD
2021-04-30 13:23:56.631 ERROR   --- [ntLoopGroup-2-1] i.b.x.s.netty.WebSocketClientHandler     : WebSocket client [id: 0x377e0c6d, L:/192.168.1.14:53999 - R:ftx.com/104.18.27.153:443] encountered exception (NullPointerException - Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null). Closing
2021-04-30 13:23:56.812  INFO   --- [ntLoopGroup-2-1] i.b.x.s.netty.WebSocketClientHandler     : WebSocket Client disconnected! [id: 0x377e0c6d, L:/192.168.1.14:53999 ! R:ftx.com/104.18.27.153:443]
2021-04-30 13:23:56.812  INFO   --- [ntLoopGroup-2-1] i.b.x.ftx.FtxStreamingService            : Reopening Websocket Client because it was closed! [id: 0x377e0c6d, L:/192.168.1.14:53999 ! R:ftx.com/104.18.27.153:443]
2021-04-30 13:23:56.812  INFO   --- [ntLoopGroup-2-1] i.b.x.ftx.FtxStreamingService            : Scheduling reconnection

**Comment by dgosset** [comment]
@makarid i saw you did a good job with orderbook. Did you try to implement the private part with FTX?

**Comment by dgosset** [comment]
Ok, i did the atuh part, and get the filled orders. I will try to finish that & propose a pull request

**Comment by makarid** [comment]
i am sorry for my late response. I have already implemented the userTrade
websocket.

Στις Παρ, 30 Απρ 2021 στις 2:50 μ.μ., ο/η Denis ***@***.***>
έγραψε:

**Comment by GodFuper** [comment]
> 
> 
> Ok, i did the atuh part, and get the filled orders. I will try to finish that & propose a pull request

Could you make a pull request? Also interested in auth on FTX

**Comment by makarid** [comment]
i will make tomorrow when i have time.

Στις Τετ, 19 Μαΐ 2021 στις 7:18 μ.μ., ο/η GodFuper ***@***.***>
έγραψε:

**Comment by elkceo** [comment]
> Ok, i did the atuh part, and get the filled orders. I will try to finish that & propose a pull request

How you did auth part?
