### ISSUE TITLE
[Binance] Problem instantiating Binance Orderbook stream

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#4104]
Hello, does anyone has a problem instantiating Binance OrderbookStreaming? I am getting the following error,i have the latest version:

2021-06-05 20:13:39 INFO  BinanceStreamingService:144 - Connecting to wss://stream.binance.com:9443/stream?streams=btcusd@ticker/btcusd@depth/btcusd@trade
2021-06-05 20:13:39 WARN  ChannelInitializer:97 - Failed to initialize a channel. Closing: [id: 0xdf5bd0f4]
java.lang.NoSuchMethodError: 'java.lang.String io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(java.lang.String, java.lang.String)'
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:147) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http.HttpVersion.<clinit>(HttpVersion.java:44) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http.HttpObjectAggregator.<clinit>(HttpObjectAggregator.java:90) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at info.bitrich.xchangestream.service.netty.NettyStreamingService$1.initChannel(NettyStreamingService.java:222) ~[classes/:?]
	at info.bitrich.xchangestream.service.netty.NettyStreamingService$1.initChannel(NettyStreamingService.java:205) ~[classes/:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.54.Final.jar:4.1.54.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-06-05 20:13:39 WARN  BinanceStreamingService:269 - Problem with connection
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]

**Comment by earce** [comment]
Do you see this on any version other then the latest?

**Comment by makarid** [comment]
Hello, i have tried again to connect to orderbook websocket but i am getting the following error.
Caused by: org.knowm.xchange.exceptions.ExchangeException: API-key format invalid. (HTTP status code: 400)
	at org.knowm.xchange.binance.BinanceErrorAdapter.adapt(BinanceErrorAdapter.java:49)
	at org.knowm.xchange.binance.service.BinanceAccountService.getAssetDetails(BinanceAccountService.java:196)
	at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:113)
	... 29 more
Caused by: org.knowm.xchange.binance.dto.BinanceException: API-key format invalid. (HTTP status code: 400)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:424)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:113)
	at com.sun.proxy.$Proxy32.assetDetail(Unknown Source)
	at org.knowm.xchange.binance.service.BinanceAccountServiceRaw.lambda$requestAssetDetail$3(BinanceAccountServiceRaw.java:91)
	at org.knowm.xchange.client.ResilienceUtils$DecorateCallableApi.call(ResilienceUtils.java:86)
	at org.knowm.xchange.binance.service.BinanceAccountServiceRaw.requestAssetDetail(BinanceAccountServiceRaw.java:95)
	at org.knowm.xchange.binance.service.BinanceAccountService.getAssetDetails(BinanceAccountService.java:194)
	... 30 more

It seems that this error happens when i am calling the assetDetails endpoint. I have try it with API keys and without and i am always getting this error. I have even delete the assetDetails call on the remoteInit at somepoint but i was still getting the same error. This error happens ONLY on streamingOrderbook.

**Comment by cymp** [comment]
Fixed here : https://github.com/knowm/XChange/pull/4198
