### ISSUE TITLE
BitZ: getTicker return error 

### ISSUE THREAD

**Issue by Aento** [knowm/XChange#4142]
Firs of all sslUri is wrong need to update it to "https://apiv2.bitz.com".

When try to getTicker I get this error:

`si.mazi.rescu.HttpStatusIOException: Cannot coerce empty String ("") to `org.knowm.xchange.bitz.dto.marketdata.BitZTicker` value (but could if coercion was enabled using `CoercionConfig`)
 at [Source: (String)"{"status":-107,"msg":"","data":"","time":1624779684,"microtime":"0.11429400 1624779684","source":"api"}"; line: 1, column: 32] (through reference chain: org.knowm.xchange.bitz.dto.marketdata.result.BitZTickerResult["data"])
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:113)
	at org.knowm.xchange.examples.interceptor.LoggingInterceptor.aroundInvoke(LoggingInterceptor.java:16)
	at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42)
	at com.sun.proxy.$Proxy35.getTickerResult(Unknown Source)
	at org.knowm.xchange.bitz.service.BitZMarketDataServiceRaw.getBitZTicker(BitZMarketDataServiceRaw.java:33)
	at exchages.BitzManager.getCryptoPairPrice(BitzManager.java:45)
	at CryptoCurrency.Stellar$Task.run(Stellar.java:84)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by walec51** [comment]
feel free to submit a PR
