### ISSUE TITLE
Parsing OrderBook Arrays

### ISSUE THREAD

**Issue by douggie** [knowm/XChange#4163]
I am extending the okex.v5 implmentation to support orderbooks.

however I am getting this error

```{"code":"0","msg":"","data":[{"asks":[["33838.5","0.02065213","0","3"],["33840.1","0.01000021","0","1"],["33842.7","0.01","0","1"],["33843.2","0.02","0","1"],["33845.2","0.00823481","0","1"],["33846","0.00443723","0","1"],["33846.9","0.01082716","0","2"],["33848.1","0.1","0","1"],["33848.2","0.05306053","0","1"],["33848.7","0.02955015","0","1"],["33849.6","0.1","0","1"],["33849.7","0.004","0","1"],["33850","0.10764359","0","3"],["33850.1","0.00023634","0","1"],["33850.4","0.00056553","0","1"],["33850.6","0.03","0","1"],["33850.7","0.25053866","0","1"],["33850.9","0.0000218","0","2"],["33851","0.0000109","0","1"],["33851.1","0.10077814","0","2"]],"bids":[["33838.4","4.47127261","0","22"],["33838.3","0.79950494","0","7"],["33836.6","0.10342734","0","1"],["33836.4","0.021","0","2"],["33836.2","0.00006469","0","1"],["33836.1","0.08292229","0","1"],["33835.6","0.03867275","0","1"],["33835.2","0.1477447","0","1"],["33834.9","0.05","0","1"],["33834.8","0.083","0","1"],["33834.3","0.03","0","1"],["33832.9","0.00004603","0","1"],["33831.9","0.01038318","0","1"],["33830.8","0.00320429","0","4"],["33830.7","0.22162149","0","1"],["33830.4","0.07","0","1"],["33830","0.01","0","1"],["33829.5","0.25055121","0","1"],["33828.5","5.3126","0","1"],["33827.5","0.00443381","0","1"]],"ts":"1625929282361"}]} 
16:01:37.714 [default] [main] DEBUG si.mazi.rescu.ResponseReader - Parsing response as org.knowm.xchange.okex.v5.dto.OkexResponse<org.knowm.xchange.okex.v5.dto.marketdata.OkexOrderbook> failed: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.knowm.xchange.okex.v5.dto.marketdata.OkexOrderbook` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"{"code":"0","msg":"","data":[{"asks":[["33838.5","0.02065213","0","3"],["33840.1","0.01000021","0","1"],["33842.7","0.01","0","1"],["33843.2","0.02","0","1"],["33845.2","0.00823481","0","1"],["33846","0.00443723","0","1"],["33846.9","0.01082716","0","2"],["33848.1","0.1","0","1"],["33848.2","0.05306053","0","1"],["33848.7","0.02955015","0","1"],["33849.6","0.1","0","1"],["33849.7","0.004","0","1"],["33850","0.10764359","0","3"],["33850.1","0.00023634","0","1"],["33850.4","0.00056553","0","1"],[""[truncated 806 chars]; line: 1, column: 29] (through reference chain: org.knowm.xchange.okex.v5.dto.OkexResponse["data"]) 
Exception in thread "main" org.knowm.xchange.okex.v5.dto.OkexException: 
	at org.knowm.xchange.okex.v5.service.OkexMarketDataServiceRaw.getOkexOrderbook(OkexMarketDataServiceRaw.java:75)
	at org.knowm.xchange.okex.v5.service.OkexMarketDataService.getOrderBook(OkexMarketDataService.java:27)
	at org.knowm.xchange.examples.okex.v5.marketdata.OkexDepthDemo.generic(OkexDepthDemo.java:35)
	at org.knowm.xchange.examples.okex.v5.marketdata.OkexDepthDemo.main(OkexDepthDemo.java:25)```


I would have thought having a custom parser for the arrays would adress this but it does not seem to be working.

`public class OkexOrderbook {

  private final List<OkexPublicOrder> asks;

  private final List<OkexPublicOrder> bids;
  private final String ts;

  @JsonCreator
  public OkexOrderbook(
      @JsonProperty("asks") List<OkexPublicOrder> asks,
      @JsonProperty("bids") List<OkexPublicOrder> bids,
      @JsonProperty("ts") String ts) {

    this.asks = null;
    this.bids = null;
    this.ts = ts;
  }

  /*  public List<OkexPublicOrder> getAsks() {
    return asks;
  }

  public List<OkexPublicOrder> getBids() {
    return bids;
  }

  @Override
  public String toString() {
    return "OkexOrderbookResponse{" + "asks=" + asks + ", bids=" + bids + '}';
  }*/
}`

any my array elements like this

`@JsonDeserialize(using = OkexPublicOrder.okexOrderDeserializer.class)
public class OkexPublicOrder {

  private final BigDecimal price;
  private final BigDecimal volume;
  private final BigDecimal liquidatedOrders;
  private final BigDecimal activeOrders;

  public OkexPublicOrder(
      BigDecimal price, BigDecimal volume, BigDecimal liquidatedOrders, BigDecimal activeOrders) {

    this.price = price;
    this.volume = volume;
    this.liquidatedOrders = liquidatedOrders;
    this.activeOrders = activeOrders;
  }

  public BigDecimal getPrice() {

    return price;
  }

  public BigDecimal getVolume() {

    return volume;
  }

  @Override
  public String toString() {
    return "OkexPublicOrder{"
        + "price="
        + price
        + ", volume="
        + volume
        + ", liquidatedOrders="
        + liquidatedOrders
        + ", activeOrders="
        + activeOrders
        + '}';
  }

  static class okexOrderDeserializer extends JsonDeserializer<OkexPublicOrder> {

    @Override
    public OkexPublicOrder deserialize(JsonParser jsonParser, DeserializationContext ctxt)
        throws IOException, JsonProcessingException {

      ObjectCodec oc = jsonParser.getCodec();
      JsonNode node = oc.readTree(jsonParser);
      if (node.isArray()) {
        BigDecimal price = new BigDecimal(node.path(0).asText());
        BigDecimal volume = new BigDecimal(node.path(1).asText());
        BigDecimal liquidatedOrders = new BigDecimal(node.path(3).asText());
        BigDecimal activeOrders = new BigDecimal(node.path(4).asText());

        return new OkexPublicOrder(price, volume, liquidatedOrders, activeOrders);
      }

      return null;
    }
  }
}`

Any pointers welcomed around how to parse the orderbooks effectivtley.

**Comment by douggie** [comment]
Doh, they come back in an array. sorted
