### ISSUE TITLE
Binance stream trading service (NOT_AUTHENTICATED)

### ISSUE THREAD

**Issue by ducanh2110** [knowm/XChange#4303]
Dear all, I have problem when I try to use streamTradingService (Binance). It always tell me that: Not_Authenticated when i try to subscribe to get my trade info. Please help me tks. 

org.knowm.xchange.exceptions.ExchangeSecurityException: Not authenticated
	at info.bitrich.xchangestream.binance.BinanceStreamingTradeService.getRawExecutionReports(BinanceStreamingTradeService.java:38) ~[xchange-stream-binance-5.0.12-20211025.161719-9.jar:na]
	at info.bitrich.xchangestream.binance.BinanceStreamingTradeService.getUserTrades(BinanceStreamingTradeService.java:54) ~[xchange-stream-binance-5.0.12-20211025.161719-9.jar:na]
	at info.bitrich.xchangestream.binance.BinanceStreamingTradeService.getUserTrades(BinanceStreamingTradeService.java:61) ~[xchange-stream-binance-5.0.12-20211025.161719-9.jar:na]

**Comment by ducanh2110** [comment]
I forgot to add ALL productsubscriptions for StreamingExchange
