### ISSUE TITLE
[xchange-okex] Need implement method getTickers(Params params)

### ISSUE THREAD

**Issue by Freeongoo** [knowm/XChange#4446]
Using some framwork with XChange and for correct work method must be implemented

getTickers(Params params) from MarketDataService

For current version [xchange-okex] not implemented

Exception:

```
org.knowm.xchange.exceptions.NotYetImplementedForExchangeException: getTicker
	at org.knowm.xchange.service.marketdata.MarketDataService.getTicker(MarketDataService.java:59)
	at tech.cassandre.trading.bot.service.MarketServiceXChangeImplementation.getTicker(MarketServiceXChangeImplementation.java:47)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at tech.cassandre.trading.bot.batch.TickerFlux.getNewValues(TickerFlux.java:61)
	at tech.cassandre.trading.bot.util.base.batch.BaseFlux.update(BaseFlux.java:76)
	at tech.cassandre.trading.bot.configuration.ScheduleAutoConfiguration.tickerFluxUpdate(ScheduleAutoConfiguration.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.ru
```

**Comment by Freeongoo** [comment]
@gmax0 could you help?

**Comment by eschava** [comment]
Please check this https://github.com/knowm/XChange/pull/4462
or this https://github.com/knowm/XChange/pull/4470 pull requests
