### ISSUE TITLE
Bitfinex nonce issues when cancelling open orders

### ISSUE THREAD

**Issue by zholmes1** [knowm/XChange#464]
```
java.io.IOException: HTTP status code was 400; response body: {"message":"Nonce is too small."}
```

After a fair amount of testing this has only happened when I cancel orders.

Getting wallets, open orders, history, and placing orders do not cause this exception. Only cancelling orders. Increasing my API call throttle (from 1 second to 5 seconds) seems to help somewhat, but still about 1/4 of the times I attempt to cancel an order I receive this error.

**Comment by douggie** [comment]
Hi, I am also getting this intermittently on placing orders, is this a time drift issue?

org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.bitfinex.v1.dto.BitfinexException: Nonce is too small.
	at org.knowm.xchange.bitfinex.v1.service.BitfinexTradeServiceRaw.sendLimitOrder(BitfinexTradeServiceRaw.java:140) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.knowm.xchange.bitfinex.v1.service.BitfinexTradeServiceRaw.placeBitfinexLimitOrder(BitfinexTradeServiceRaw.java:104) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.knowm.xchange.bitfinex.v1.service.BitfinexTradeService.placeLimitOrder(BitfinexTradeService.java:80) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.cryptocoinpartners.module.xchange.XchangeOrderService.handleSpecificOrder(XchangeOrderService.java:199) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.cryptocoinpartners.module.BaseOrderService.placeOrder(BaseOrderService.java:236) [cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.cryptocoinpartners.module.BaseOrderService.updateRestingOrders(BaseOrderService.java:2657) [cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.cryptocoinpartners.module.BaseOrderService.handleTrade(BaseOrderService.java:2225) [cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
