### ISSUE TITLE
OKX NumberFormatException on GetOrder

### ISSUE THREAD

**Issue by Wayruha** [knowm/XChange#4718]
Getting NumberFormatException of GetOrder in case if order type is MARKET (price="").
There's a piece of code `new BigDecimal(order.getPrice())` which is failing because of illegal argument "".
`java.lang.NumberFormatException: null
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:624)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:401)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:834)
	at org.knowm.xchange.okex.OkexAdapters.adaptOrder(OkexAdapters.java:79)
	at org.knowm.xchange.okex.service.OkexTradeService.getOrder(OkexTradeService.java:121)

**Comment by rizer1980** [comment]
hi.
How is it that the answer comes with an empty field px (price)?

**Comment by Wayruha** [comment]
I can't answer this question as I'm not a representative of Okx or XChange. That's just a fact which I got for MARKET order

**Comment by rizer1980** [comment]
Is the error permanent or did it happen once?
If permanent, show your code where it occurs.
and attach debug logs. such that the request and response from the OKX server were visible
