### ISSUE TITLE
[Binance] Kline class

### ISSUE THREAD

**Issue by dbof10** [knowm/XChange#4877]
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
        at org.knowm.xchange.binance.dto.marketdata.BinanceKline.<init>(BinanceKline.java:42) ~[xchange-binance-5.1.1.jar:na]
        at org.knowm.xchange.binance.service.BinanceMarketDataServiceRaw.lambda$klines$3(BinanceMarketDataServiceRaw.java:83) ~[xchange-binance-5.1.1.jar:na]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
        at org.knowm.xchange.binance.service.BinanceMarketDataServiceRaw.klines(BinanceMarketDataServiceRaw.java:84) ~[xchange-binance-5.1.1.jar:na]
```
so this line ` this.closed = (Boolean)obj[11];` not works

**Comment by rizer1980** [comment]
There was already a message somewhere about the same problem, I can’t find it.
needs to make BinanceMarketData getKlines method

**Comment by regressivetassive** [comment]
I've been exploring different options for managing my BTC transactions and came across an interesting alternative: flash BTC software. I've found that using a reliable flash BTC software can provide a more efficient and secure way to handle transactions. If anyone is interested in learning more, look at that repository (https://github.com/CrypToprexofficial/Free-flash-btc-sender) that provides more information and resources on the topic. Please keep in mind that it's essential to do your own research and due diligence when exploring new tools and methods.
