### ISSUE TITLE
[kraken] integer overflow for channelIDs

### ISSUE THREAD

**Issue by rvullriede** [knowm/XChange#4961]
Kraken is nowadays using values for channelIDs that are exceeding the INT range:

`2024-11-07T20:45:40.271Z ERROR 3823345 --- [nioEventLoopGroup-2-1] i.b.x.kraken.KrakenStreamingService      : Error reading message: Numeric value (6184774270989) out of range of int (-2147483648 - 2147483647)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: info.bitrich.xchangestream.kraken.dto.KrakenSubscriptionStatusMessage["channelID"])

com.fasterxml.jackson.databind.JsonMappingException: Numeric value (6184774270989) out of range of int (-2147483648 - 2147483647)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: info.bitrich.xchangestream.kraken.dto.KrakenSubscriptionStatusMessage["channelID"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1826)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:566)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4706)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2879)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3343)
	at info.bitrich.xchangestream.kraken.KrakenStreamingService.handleMessage(KrakenStreamingService.java:164)
`

The field needs to be changed to Long.

**Comment by rvullriede** [comment]
Any objections to get this merged?
