### ISSUE TITLE
coinfloor demo problem

### ISSUE THREAD

**Issue by johnpmc** [knowm/XChange#511]
When I run the CoinfloorDemo2 example from Xchange I get the error below:
The classpath contains: bcprov-jdk15on-1.50.jar

Thanks for any help or advice.

Exception in thread "main" java.lang.NoSuchMethodError: org.bouncycastle.util.encoders.Base64.toBase64String([B)Ljava/lang/String;
        at com.xeiam.xchange.coinfloor.CoinfloorUtils.bigIntegerToBase64(CoinfloorUtils.java:112)
        at com.xeiam.xchange.coinfloor.CoinfloorUtils.buildSignature(CoinfloorUtils.java:97)
        at com.xeiam.xchange.coinfloor.streaming.RequestFactory$CoinfloorAuthenticationRequest.<init>(RequestFactory.java:69)
        at com.xeiam.xchange.coinfloor.streaming.CoinfloorStreamingExchangeService.authenticate(CoinfloorStreamingExchangeService.java:125)

**Comment by 1228857713** [comment]
i hava some problem too,but not this project ,are you sloving this problem ?  if you are. can you tell me how to !!!! thanks
